# Import libraries

In [149]:
import pandas as pd
from datetime import datetime,timedelta

import time

# Read csv files

In [165]:
#read day 1 data
df0 = pd.read_csv("D:\\Research Project\\Datasets\\Flood intensity\\data url\\Day 1 file\day 1 4924 not null rows processed.csv")
print(len(df0)) ####4924
df0.head()

4924

,Unnamed: 0,Unnamed: 0.1,ID,GlideNumber,Country,OtherCountry,long,lat,Area,Began,...,Time,Temperature,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Precipitation,Condition
0,0,0,1,0,Algeria,0,5.23026,35.81420,92615.67,1985-01-01,...,1594868010,66.2,NaN,88,NaN,1.5,NaN,30.12,NaN,Clouds
1,1,1,2,0,Brazil,0,-45.34890,-18.71110,678498.82,1985-01-15,...,1594868015,68.59,NaN,63,NaN,1.74,NaN,30.12,NaN,Clouds
2,2,2,3,0,Phillipines,0,122.97400,10.02070,12846.03,1985-01-20,...,1594868015,77.79,NaN,78,NaN,1.9,NaN,29.8,NaN,Clouds
3,3,3,4,0,Indonesia,0,124.60600,1.01489,16542.12,1985-02-04,...,1594868015,89.6,NaN,55,NaN,1,NaN,29.83,NaN,Clouds
4,4,4,5,0,Mozambique,0,32.34910,-25.86930,20082.21,1985-02-09,...,1594868015,53.29,NaN,66,NaN,5.1,NaN,30.56,NaN,Clear

In [167]:
#drop unnecessary columns
df0.drop(df0.columns[[0,1,3,5,11,16,17,18]], axis=1, inplace=True)
df0

,ID,Country,long,lat,Area,Began,Ended,Dead,Displaced,MainCause,Severity,Temperature,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Precipitation,Condition
0,1,Algeria,5.23026,35.814200,92615.67,1985-01-01,1985-01-05,26,3000,Heavy rain,1.0,66.2,NaN,88,NaN,1.5,NaN,30.12,NaN,Clouds
1,2,Brazil,-45.34890,-18.711100,678498.82,1985-01-15,1985-02-02,229,80000,Heavy rain,2.0,68.59,NaN,63,NaN,1.74,NaN,30.12,NaN,Clouds
2,3,Phillipines,122.97400,10.020700,12846.03,1985-01-20,1985-01-21,43,444,Torrential rain,1.0,77.79,NaN,78,NaN,1.9,NaN,29.8,NaN,Clouds
3,4,Indonesia,124.60600,1.014890,16542.12,1985-02-04,1985-02-18,21,300,Torrential rain,1.0,89.6,NaN,55,NaN,1,NaN,29.83,NaN,Clouds
4,5,Mozambique,32.34910,-25.869300,20082.21,1985-02-09,1985-02-11,19,0,Heavy rain,2.0,53.29,NaN,66,NaN,5.1,NaN,30.56,NaN,Clear
5,6,Comoros islands,43.36000,-11.651600,1035.61,1985-02-16,1985-02-28,2,35000,Tropical cyclone,1.0,68.0,NaN,86,NaN,8.8,NaN,30.06,NaN,Rain
6,7,New Zealand,175.73400,-37.230500,7871.37,1985-02-17,1985-02-18,4,200,Heavy rain,1.0,53.01,NaN,87,NaN,9.39,NaN,29.91,NaN,Rain
7,8,Indonesia,108.14000,-7.040080,77091.11,1985-02-19,1985-02-23,10,2000,Heavy rain,1.0,67.84,NaN,87,NaN,1.03,NaN,29.83,NaN,Clouds
8,10,Bolivia,-63.28870,-21.224400,69706.89,1985-02-25,1985-02-28,2,1000,Heavy Rain,1.0,61.56,NaN,49,NaN,1.09,NaN,29.94,NaN,Clouds
9,13,USA,-96.78450,29.604400,141508.00,1985-03-14,1985-03-15,0,0,Heavy rain,1.0,83.19,NaN,74,NaN,3.1,NaN,29.97,NaN,Clear
10,15,Brazil,-48.09870,-4.135190,1970402.21,1985-04-02,1985-04-17,32,700000,Heavy rain,2.0,72.09,NaN,81,NaN,1.2,NaN,29.91,NaN,Clouds
11,17,China,127.89700,48.091700,300325.08,1985-04-21,1985-04-29,0,200,Ice jam/break-up,1.0,87.44,NaN,41,NaN,3.72,NaN,29.59,NaN,Clouds
12,20,USA,-66.70600,18.229100,1423.92,1985-05-19,1985-05-20,2,4500,Heavy rain,1.0,74.88,NaN,94,NaN,0.89,NaN,28.29,NaN,Clear
13,21,China,109.57000,25.669400,458666.21,1985-05-26,1985-06-06,64,10000,Heavy rain,2.0,87.8,NaN,62,NaN,6,NaN,29.68,NaN,Clouds
14,22,Argentina,-58.97350,-35.439200,78653.41,1985-05-30,1985-06-01,25,100000,Heavy rain,2.0,47.5,NaN,60,NaN,3.12,NaN,30.18,NaN,Clouds
15,23,Bangladesh,91.85420,24.649700,8910.30,1985-06-03,1985-06-22,7,100000,Heavy rain,2.0,85.08,NaN,78,NaN,2.38,NaN,29.68,NaN,Rain
16,26,Philippines,120.91600,14.741700,7768.19,1985-06-22,1985-06-30,98,130000,Tropical cyclone,1.0,91.0,NaN,70,NaN,0.45,NaN,29.74,NaN,Clouds
17,27,India,75.09370,14.539800,254234.60,1985-06-23,1985-06-27,95,25000,Heavy rain,1.0,71.76,NaN,90,NaN,3.86,NaN,29.68,NaN,Clouds
18,28,China,109.97400,27.788200,290679.68,1985-06-28,1985-07-10,275,60000,Heavy rain,2.0,89.28,NaN,59,NaN,4.44,NaN,29.65,NaN,Clouds
19,29,Bangladesh,89.98530,22.617600,6446.85,1985-07-03,1985-07-04,2,77000,Heavy rain,1.0,88.25,NaN,65,NaN,2.83,NaN,29.62,NaN,Clouds
20,30,West Germany,6.50952,50.713400,1927.64,1985-07-06,1985-07-07,3,0,Heavy rain,1.0,55.85,NaN,87,NaN,1,NaN,30.0,NaN,Clouds
21,32,Chad,21.55090,11.672700,15243.93,1985-07-13,1985-07-16,0,1600,Heavy rain,1.0,70.54,NaN,87,NaN,2.13,NaN,29.91,NaN,Rain
22,33,India,76.91030,32.835300,117441.17,1985-07-18,1985-07-30,340,20000,Heavy rain,1.0,38.35,NaN,74,NaN,1.96,NaN,29.85,NaN,Clear
23,34,Sudan,24.91390,13.489000,63577.12,1985-07-19,1985-07-22,0,0,Heavy rain,1.0,77.68,NaN,52,NaN,3.14,NaN,29.85,NaN,Clouds
24,35,China,125.15600,42.695300,994498.21,1985-07-20,1985-09-02,200,2000000,Tropical cyclone,2.0,85.98,NaN,43,NaN,1.42,NaN,29.65,NaN,Clear
25,36,Bangladesh,90.19990,23.102800,5663.46,1985-07-21,1985-08-17,15,175000,Heavy rain,1.0,87.24,NaN,71,NaN,3.19,NaN,29.62,NaN,Clouds
26,38,China,120.37600,31.511200,58279.12,1985-08-01,1985-08-02,3,200000,Heavy rain,1.0,76.68,NaN,75,NaN,0.45,NaN,29.53,NaN,Rain
27,40,Nepal,87.12580,27.504900,12487.89,1985-08-04,1985-08-05,3,160,Heavy Rain,2.0,73.2,NaN,75,NaN,1.04,NaN,29.77,NaN,Rain
28,41,China,100.79700,23.525500,146691.46,1985-08-06,1985-08-09,283,14000,Heavy rain,1.0,72.37,NaN,83,NaN,1.6,NaN,29.74,NaN,Rain
29,42,Austria,12.20660,47.315500,15151.05,1985-08-07,1985-08-08,12,0,Heavy rain,2.0,53.01,NaN,97,NaN,0.56,NaN,29.94,NaN,Rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4894,4870,Zimbabwe,27.78490,-18.245500,73436.23,2020-02-11,2020-02-17,1,160,Heavy Rain,1.0,80,73,93,NE,2,3,30,0.1,Moderate or heavy rain shower
4895,4872,Mozambique,35.28210,-18.013200,172916.51,2020-02-12,2020-02-17,2,2000,Heavy Rain,1.5,75,74,98,SE,4,8,30,0.0,Light rain shower
4896,4873,Australia,148.60700,-27.492900,816540.49,2020-02-07,2020-02-17,1,0,Heavy Rain,1.0,80,67,86,E,14,21,30,0.0,Moderate or heavy rain shower
4897,4874,Burundi,29.98700,-3.407660,17373.89,2020-02-07,2020-02-17,3,1000,Heavy Rain,1.5,71,58,95,WNW,2,3,31,0.0,Partly cloudy
4898,4875,Tanzania,35.28210,-7.773570,266334.32,2020-02-01,2020-02-17,40,15000,Heavy Rain,2.0,65,60,94,SSE,3,6,30,0.0,Mist
4899,4879,Pakistan,71.03650,33.302600,116828.75,2020-03-06,2020-03-17,33,1200,Heavy Rain,1.5,55,44,79,NNW,3,5,30,0.0,Partly cloudy
4900,4882,Zambia,29.96230,-10.250400,101083.20,2020-03-04,2020-03-17,0,0,Heavy Rain,1.5,73,62,94,W,2,5,30,0.0,Light rain shower
4901,4884,Burundi,30.08600,-3.085660,13769.59,2020-03-02,2020-03-08,1,185,Heavy Rain,1.5,70,61,95,E,4,8,30,0.1,Moderate rain at times
4902,4885,Rwanda,29.86330,-1.994450,15283.09,2020-03-02,2020-03-05,10,0,Heavy Rain,1.5,72,62,98,S,2,3,30,0.1,Light rain shower
4903,4888,Vietnam,105.18300,20.691000,50183.18,2020-03-02,2020-03-10,2,1000,Heavy Rain,1.0,75,70,88,SE,3,4,30,0.0,Cloudy
4904,4892,Papua New Guinea,146.75200,-6.925130,14567.65,2020-04-01,2020-04-03,0,0,Heavy Rain,1.0,82,73,86,NW,7,12,30,0.0,Light rain shower
4905,4894,Afghanistan,65.64240,33.826000,220551.72,2020-03-21,2020-04-03,11,1200,Heavy Rain,1.5,41,23,86,SE,3,6,31,0.0,Patchy light snow
4906,4895,Zambia,30.90250,-10.090100,91521.53,2020-03-04,2020-04-24,0,0,Heavy Rain,1.5,68,62,97,NW,4,9,30,0.0,Patchy rain possible
4907,4896,Democratic Republic of Congo,26.74560,-3.244940,180311.71,2020-03-17,2020-04-03,36,78000,Heavy Rain,2.0,70,71,99,NE,2,4,30,0.1,Moderate or heavy rain shower
4908,4897,Kenya,36.59350,1.163430,154389.90,2020-03-27,2020-04-27,1,3000,Heavy Rain,1.5,58,59,93,SE,3,4,30,0.1,Moderate rain at times
4909,4898,Peru,-76.88010,-7.010730,152175.01,2020-03-28,2020-04-02,0,120,Heavy Rain,1.5,82,71,98,W,2,3,30,0.1,Moderate or heavy rain shower
4910,4900,Tanzania,34.21820,-4.512360,184333.48,2020-04-24,2020-04-27,2,10000,Heavy Rain,1.5,71,63,94,ENE,4,6,30,0.0,Patchy rain possible
4911,4901,Djibouti,42.68040,11.685100,10321.78,2020-04-21,2020-04-26,8,0,Torrential Rain,2.0,77,76,85,ENE,9,12,30,0.0,Thundery outbreaks possible
4912,4902,Burkina Faso,-1.11554,13.343200,42577.65,2020-04-19,2020-04-26,0,2000,Torrential Rain,1.5,96,53,26,SW,10,17,30,0.0,Partly cloudy
4913,4903,Burundi,29.93750,-2.763120,41569.31,2020-04-19,2020-04-26,9,0,Heavy Rain,1.5,66,60,97,WSW,2,5,30,0.0,Mist
4914,4907,New Caledonia,165.85400,-21.488300,8299.71,2020-04-18,2020-04-22,0,0,Torrential Rain,1.0,77,69,80,E,8,10,30,0.0,Cloudy
4915,4912,Chad,18.08540,9.627940,134488.38,2020-04-20,2020-04-26,0,2062,Heavy Rain,1.0,98,57,37,SSW,9,14,30,0.0,Partly cloudy
4916,4913,Uzbekistan,55.84400,41.245100,84662.22,2020-05-01,2020-05-11,4,70000,Dam break,2.0,60,45,47,ESE,11,19,30,0.0,Partly cloudy
4917,4914,Sri Lanka,80.85970,7.835490,46625.90,2020-05-17,2020-05-20,2,1100,Tropical Storm Amphan,1.5,86,73,82,SW,15,24,30,0.0,Partly cloudy
4918,4916,Democratic Republic Congo,17.61530,-3.822620,84572.69,2020-05-16,2020-05-20,0,500,Heavy Rain,1.5,87,70,81,SSW,2,3,30,0.0,Partly cloudy
4919,4917,Algeria,12.66660,31.683700,91355.80,2020-05-16,2020-05-18,1,0,Heavy Rain,1.0,99,33,14,SE,15,30,30,0.0,Clear
4920,4918,Ecuador,-77.99360,-2.683770,24825.78,2020-05-16,2020-05-19,2,15,Heavy Rain,1.0,49,51,90,ESE,4,6,30,0.0,Light rain shower
4921,4924,Cental African Republic,17.02140,4.582310,65353.26,2020-05-24,2020-05-30,3,0,Torrential Rain,1.0,78,68,92,SSW,3,6,30,0.0,Patchy rain possible
4922,4925,Uganda,31.02630,0.013018,47454.12,2020-05-21,2020-05-25,8,300,Torrential Rain,1.5,69,61,92,SW,2,5,30,0.0,Patchy rain possible
4923,4928,El Salvador,-89.62300,17.391100,253817.46,2020-06-02,2020-06-03,0,0,Tropical Storm Cristobal,1.5,76,72,99,W,3,6,30,0.3,Torrential rain shower

In [168]:
#convert string fields into date field
#df1['Ended'] = df1['Ended'].astype(date)
df0['Ended'] =  pd.to_datetime(df0['Ended'])
df0['Began'] = df0['Began'].astype('datetime64[ns]')
#Get the flood duration
df0['Duration'] = (df0['Ended']  - df0['Began']).astype(str)
df0.dtypes

ID                        int64
Country                  object
long                    float64
lat                     float64
Area                    float64
Began            datetime64[ns]
Ended            datetime64[ns]
Dead                      int64
Displaced                 int64
MainCause                object
Severity                float64
Temperature              object
Dew Point                object
Humidity                 object
Wind                     object
Wind Speed               object
Wind Gust                object
Pressure                 object
Precipitation            object
Condition                object
Duration                 object
dtype: object

In [169]:
#Calculate Flood Duration
for i, row in df0.iterrows():
    Duration = df0.loc[i,"Duration"]
    df0.loc[i,"Duration"]= int(Duration[:2])

In [170]:
#Calculate Area Affected oer Day
df0['Area_Affected_per_day'] = round((df0['Area']  / df0['Duration']),2)

df0.dtypes

ID                                int64
Country                          object
long                            float64
lat                             float64
Area                            float64
Began                    datetime64[ns]
Ended                    datetime64[ns]
Dead                              int64
Displaced                         int64
MainCause                        object
Severity                        float64
Temperature                      object
Dew Point                        object
Humidity                         object
Wind                             object
Wind Speed                       object
Wind Gust                        object
Pressure                         object
Precipitation                    object
Condition                        object
Duration                          int64
Area_Affected_per_day           float64
dtype: object

In [171]:
#data cleaning - removed Ã‚Â F values from Temperature

df0['Temperature']=df0['Temperature'].replace('Ã‚','',regex=True)
df0['Temperature']=df0['Temperature'].replace('F','',regex=True)


#data cleaning - removed Ã‚Â F values from Dew Point
df0['Dew Point'] = df0['Dew Point'].str.translate(str.maketrans({'Ã‚':''}))
df0['Dew Point'] = df0['Dew Point'].str.translate(str.maketrans({'F':''}))

#data cleaning - removed Ã‚Â % values from Humidity
df0['Humidity'] = df0['Humidity'].str.translate(str.maketrans({'Ã‚':''}))
df0['Humidity'] = df0['Humidity'].str.translate(str.maketrans({'%':''}))

#data cleaning - removed Ã‚Â mph values from Wind Speed
df0['Wind Speed'] = df0['Wind Speed'].str.translate(str.maketrans({'Ã‚':''}))
df0['Wind Speed'] = df0['Wind Speed'].str.translate(str.maketrans({'m':''}))
df0['Wind Speed'] = df0['Wind Speed'].str.translate(str.maketrans({'p':''}))
df0['Wind Speed'] = df0['Wind Speed'].str.translate(str.maketrans({'h':''}))

#data cleaning - removed Ã‚Â mph values from Wind Gust
df0['Wind Gust'] = df0['Wind Gust'].str.translate(str.maketrans({'Ã‚':''}))
df0['Wind Gust'] = df0['Wind Gust'].str.translate(str.maketrans({'m':''}))
df0['Wind Gust'] = df0['Wind Gust'].str.translate(str.maketrans({'p':''}))
df0['Wind Gust'] = df0['Wind Gust'].str.translate(str.maketrans({'h':''}))

#data cleaning - removed Ã‚Â in values from Pressure
df0['Pressure'] = df0['Pressure'].str.translate(str.maketrans({'Ã‚':''}))
df0['Pressure'] = df0['Pressure'].str.translate(str.maketrans({'i':''}))
df0['Pressure'] = df0['Pressure'].str.translate(str.maketrans({'n':''}))

#data cleaning - removed Ã‚Â in values from Precipitation
df0['Precipitation']= df0['Precipitation'].str.translate(str.maketrans({'Ã‚':''}))
df0['Precipitation']= df0['Precipitation'].str.translate(str.maketrans({'i':''}))
df0['Precipitation']= df0['Precipitation'].str.translate(str.maketrans({'n':''}))

In [172]:
#verify if data is cleaned or not
df0[df0['ID']==2324]

,ID,Country,long,lat,Area,Began,Ended,Dead,Displaced,MainCause,...,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Precipitation,Condition,Duration,Area_Affected_per_day
2802,2324,USA,-115.508,35.5295,34209.05,2003-08-19,2003-08-21,0,0,Torrential Rain,...,55,24,SSW,12,0,27.46,0.0,Fair,2,17104.53

In [173]:
df0.dtypes

ID                                int64
Country                          object
long                            float64
lat                             float64
Area                            float64
Began                    datetime64[ns]
Ended                    datetime64[ns]
Dead                              int64
Displaced                         int64
MainCause                        object
Severity                        float64
Temperature                      object
Dew Point                        object
Humidity                         object
Wind                             object
Wind Speed                       object
Wind Gust                        object
Pressure                         object
Precipitation                    object
Condition                        object
Duration                          int64
Area_Affected_per_day           float64
dtype: object

In [174]:
df0.columns =['ID','Country','longitude','latitude','Area','Began','Ended','Dead','Displaced','MainCause','Severity','Day0_Temperature','Day0_Dew_Point','Day0_Humidity','Day0_Wind','Day0_Wind_Speed','Day0_Wind_Gust','Day0_Pressure','Day0_Precipitation','Day0_Condition','Duration','Area_Affected_per_day']

In [175]:
df0.dtypes

ID                                int64
Country                          object
longitude                       float64
latitude                        float64
Area                            float64
Began                    datetime64[ns]
Ended                    datetime64[ns]
Dead                              int64
Displaced                         int64
MainCause                        object
Severity                        float64
Day0_Temperature                 object
Day0_Dew_Point                   object
Day0_Humidity                    object
Day0_Wind                        object
Day0_Wind_Speed                  object
Day0_Wind_Gust                   object
Day0_Pressure                    object
Day0_Precipitation               object
Day0_Condition                   object
Duration                          int64
Area_Affected_per_day           float64
dtype: object

In [176]:
#read day minus 1 data
df1 = pd.read_csv("D:\Research Project\Datasets\Flood intensity\data url\Day minus 1 file\dayminus1 4926 not null rows processed.csv")
print(len(df1)) ####4926
df1.head()

4926

,Unnamed: 0,Unnamed: 0.1,ID,GlideNumber,Country,OtherCountry,long,lat,Area,Began,...,Time,Temperature,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Precipitation,Condition
0,0,0,1,0,Algeria,0,5.23026,35.81420,92615.67,1985-01-01,...,1594891452,71.60,NaN,83.0,NaN,3.10,NaN,30.15,NaN,Clouds
1,1,1,2,0,Brazil,0,-45.34890,-18.71110,678498.82,1985-01-15,...,1594891457,64.27,NaN,78.0,NaN,1.96,NaN,30.15,NaN,Clouds
2,2,2,3,0,Phillipines,0,122.97400,10.02070,12846.03,1985-01-20,...,1594891457,75.11,NaN,94.0,NaN,1.24,NaN,29.74,NaN,Rain
3,3,3,4,0,Indonesia,0,124.60600,1.01489,16542.12,1985-02-04,...,1594891458,80.60,NaN,88.0,NaN,1.00,NaN,29.77,NaN,Clouds
4,4,4,5,0,Mozambique,0,32.34910,-25.86930,20082.21,1985-02-09,...,1594891458,68.65,NaN,43.0,NaN,5.10,NaN,30.62,NaN,Clouds

In [177]:
#drop unrequired columns
df1.drop(df1.columns[[0,1,3,5,11,16,17,18]], axis=1, inplace=True)
df1

,ID,Country,long,lat,Area,Began,Ended,Dead,Displaced,MainCause,Severity,Temperature,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Precipitation,Condition
0,1,Algeria,5.230260,35.81420,92615.67,1985-01-01,1985-01-05,26,3000,Heavy rain,1.0,71.60,NaN,83.0,NaN,3.10,NaN,30.15,NaN,Clouds
1,2,Brazil,-45.348900,-18.71110,678498.82,1985-01-15,1985-02-02,229,80000,Heavy rain,2.0,64.27,NaN,78.0,NaN,1.96,NaN,30.15,NaN,Clouds
2,3,Phillipines,122.974000,10.02070,12846.03,1985-01-20,1985-01-21,43,444,Torrential rain,1.0,75.11,NaN,94.0,NaN,1.24,NaN,29.74,NaN,Rain
3,4,Indonesia,124.606000,1.01489,16542.12,1985-02-04,1985-02-18,21,300,Torrential rain,1.0,80.60,NaN,88.0,NaN,1.00,NaN,29.77,NaN,Clouds
4,5,Mozambique,32.349100,-25.86930,20082.21,1985-02-09,1985-02-11,19,0,Heavy rain,2.0,68.65,NaN,43.0,NaN,5.10,NaN,30.62,NaN,Clouds
5,6,Comoros islands,43.360000,-11.65160,1035.61,1985-02-16,1985-02-28,2,35000,Tropical cyclone,1.0,78.80,NaN,78.0,NaN,10.30,NaN,30.06,NaN,Clouds
6,7,New Zealand,175.734000,-37.23050,7871.37,1985-02-17,1985-02-18,4,200,Heavy rain,1.0,51.62,NaN,83.0,NaN,7.15,NaN,29.91,NaN,Rain
7,8,Indonesia,108.140000,-7.04008,77091.11,1985-02-19,1985-02-23,10,2000,Heavy rain,1.0,67.86,NaN,93.0,NaN,1.75,NaN,29.71,NaN,Rain
8,10,Bolivia,-63.288700,-21.22440,69706.89,1985-02-25,1985-02-28,2,1000,Heavy Rain,1.0,59.09,NaN,52.0,NaN,1.32,NaN,29.91,NaN,Clouds
9,13,USA,-96.784500,29.60440,141508.00,1985-03-14,1985-03-15,0,0,Heavy rain,1.0,77.25,NaN,94.0,NaN,1.50,NaN,30.03,NaN,Clouds
10,15,Brazil,-48.098700,-4.13519,1970402.21,1985-04-02,1985-04-17,32,700000,Heavy rain,2.0,67.08,NaN,94.0,NaN,0.59,NaN,29.88,NaN,Clear
11,17,China,127.897000,48.09170,300325.08,1985-04-21,1985-04-29,0,200,Ice jam/break-up,1.0,83.21,NaN,54.0,NaN,3.69,NaN,29.53,NaN,Clouds
12,20,USA,-66.706000,18.22910,1423.92,1985-05-19,1985-05-20,2,4500,Heavy rain,1.0,71.69,NaN,93.0,NaN,0.89,NaN,28.26,NaN,Clear
13,21,China,109.570000,25.66940,458666.21,1985-05-26,1985-06-06,64,10000,Heavy rain,2.0,91.40,NaN,55.0,NaN,6.00,NaN,29.59,NaN,Clouds
14,22,Argentina,-58.973500,-35.43920,78653.41,1985-05-30,1985-06-01,25,100000,Heavy rain,2.0,46.13,NaN,64.0,NaN,2.33,NaN,30.15,NaN,Clouds
15,23,Bangladesh,91.854200,24.64970,8910.30,1985-06-03,1985-06-22,7,100000,Heavy rain,2.0,90.57,NaN,69.0,NaN,3.54,NaN,29.53,NaN,Rain
16,26,Philippines,120.916000,14.74170,7768.19,1985-06-22,1985-06-30,98,130000,Tropical cyclone,1.0,92.57,NaN,64.0,NaN,3.13,NaN,29.68,NaN,Rain
17,27,India,75.093700,14.53980,254234.60,1985-06-23,1985-06-27,95,25000,Heavy rain,1.0,74.12,NaN,88.0,NaN,5.67,NaN,29.62,NaN,Rain
18,28,China,109.974000,27.78820,290679.68,1985-06-28,1985-07-10,275,60000,Heavy rain,2.0,91.35,NaN,61.0,NaN,3.80,NaN,29.50,NaN,Clouds
19,29,Bangladesh,89.985300,22.61760,6446.85,1985-07-03,1985-07-04,2,77000,Heavy rain,1.0,92.17,NaN,57.0,NaN,5.68,NaN,29.50,NaN,Rain
20,30,West Germany,6.509520,50.71340,1927.64,1985-07-06,1985-07-07,3,0,Heavy rain,1.0,59.72,NaN,93.0,NaN,3.10,NaN,30.03,NaN,Mist
21,32,Chad,21.550900,11.67270,15243.93,1985-07-13,1985-07-16,0,1600,Heavy rain,1.0,73.96,NaN,84.0,NaN,2.31,NaN,29.97,NaN,Clouds
22,33,India,76.910300,32.83530,117441.17,1985-07-18,1985-07-30,340,20000,Heavy rain,1.0,45.79,NaN,64.0,NaN,4.28,NaN,29.68,NaN,Rain
23,34,Sudan,24.913900,13.48900,63577.12,1985-07-19,1985-07-22,0,0,Heavy rain,1.0,88.57,NaN,31.0,NaN,3.80,NaN,29.91,NaN,Clouds
24,35,China,125.156000,42.69530,994498.21,1985-07-20,1985-09-02,200,2000000,Tropical cyclone,2.0,84.42,NaN,58.0,NaN,2.91,NaN,29.62,NaN,Clouds
25,36,Bangladesh,90.199900,23.10280,5663.46,1985-07-21,1985-08-17,15,175000,Heavy rain,1.0,90.25,NaN,67.0,NaN,4.55,NaN,29.50,NaN,Rain
26,38,China,120.376000,31.51120,58279.12,1985-08-01,1985-08-02,3,200000,Heavy rain,1.0,78.66,NaN,67.0,NaN,2.87,NaN,29.53,NaN,Clouds
27,40,Nepal,87.125800,27.50490,12487.89,1985-08-04,1985-08-05,3,160,Heavy Rain,2.0,77.29,NaN,67.0,NaN,2.03,NaN,29.62,NaN,Rain
28,41,China,100.797000,23.52550,146691.46,1985-08-06,1985-08-09,283,14000,Heavy rain,1.0,74.95,NaN,88.0,NaN,1.76,NaN,29.56,NaN,Rain
29,42,Austria,12.206600,47.31550,15151.05,1985-08-07,1985-08-08,12,0,Heavy rain,2.0,58.30,NaN,82.0,NaN,0.50,NaN,30.06,NaN,Clouds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4896,4766,Mongolia,111.071000,47.20370,85984.41,2019-06-15,2019-06-19,0,0,Heavy Rain,1.0,74.00,42.0,40.0,SW,9.00,14.0,30.00,0.0,Partly cloudy
4897,4769,Bangladesh,89.351800,25.18590,34209.79,2019-07-10,2019-07-13,0,10000,Monsoonal Rain,1.0,86.00,78.0,85.0,S,13.00,28.0,30.00,0.4,Torrential rain shower
4898,4773,Pakistan,73.362400,36.14030,30502.40,2019-07-07,2019-07-13,0,100,Glacial Lake Outburst,2.0,64.00,41.0,49.0,W,3.00,4.0,30.00,0.0,Partly cloudy
4899,4777,Russia,102.485000,58.91110,413323.05,2019-06-25,2019-07-10,18,3000,Heavy Rain,1.5,78.00,45.0,51.0,ENE,5.00,11.0,30.00,0.0,Partly cloudy
4900,4778,Yemen,43.571200,15.11830,30368.53,2019-07-30,2019-08-09,12,500,Torrential Rain,1.5,76.00,55.0,59.0,W,2.00,3.0,30.00,0.0,Partly cloudy
4901,4779,Guatamala,-90.971600,15.09940,16345.25,2019-08-04,2019-08-09,0,300,Torrential Rain,1.0,67.00,47.0,96.0,E,2.00,5.0,30.00,0.0,Light rain shower
4902,4783,Brazil,-36.350300,-8.49416,57167.37,2019-07-22,2019-08-01,8,0,Heavy Rain,1.5,71.00,64.0,94.0,SE,11.00,16.0,31.00,0.0,Light rain shower
4903,4786,Sudan,33.921200,14.82620,228503.64,2019-08-07,2019-08-29,54,100000,Heavy Rain,1.5,84.00,66.0,61.0,S,9.00,11.0,30.00,0.0,Partly cloudy
4904,4787,Mauritania,-12.448100,15.64270,25276.68,2019-08-25,2019-08-29,5,0,Heavy Ran,1.0,89.00,69.0,53.0,WSW,17.00,24.0,30.00,0.0,Cloudy
4905,4788,Morocco,-9.330380,28.63270,57765.53,2019-08-20,2019-08-28,7,0,Torrential Rain,1.0,91.00,42.0,29.0,W,4.00,9.0,30.00,0.0,Partly cloudy
4906,4790,Bahamas,-78.426600,26.62200,1721.40,2019-09-01,2019-09-04,5,30000,Tropical Storm Dorian,2.0,85.00,76.0,75.0,E,17.00,23.0,30.00,0.0,Patchy rain possible
4907,4791,Algeria,7.829230,36.85520,1566.33,2019-09-01,2019-09-02,0,40,Torrential Rain,1.0,81.00,70.0,82.0,SW,1.00,1.0,31.00,0.0,Partly cloudy
4908,4792,Central African Republic,17.145200,7.22255,70469.71,2019-08-19,2019-08-22,1,725,Heavy Rain,1.0,73.00,68.0,96.0,WSW,1.00,3.0,30.00,0.0,Light rain shower
4909,4795,Cambodia,105.479000,14.59050,146785.96,2019-09-05,2019-09-14,7,50000,Heavy Rain,1.5,73.00,71.0,99.0,SSW,4.00,8.0,30.00,0.2,Moderate rain
4910,4796,Spain,-1.090800,38.04960,9114.70,2019-09-12,2019-09-14,3,300,Torrential Rain,1.5,69.00,39.0,37.0,NNW,17.00,25.0,30.00,0.0,Patchy light rain with thunder
4911,4801,Camaroon,14.621300,12.15780,10557.47,2019-10-01,2019-10-15,0,0,Heavy Rain,1.0,84.00,68.0,73.0,S,3.00,5.0,30.00,0.0,Patchy rain possible
4912,4802,Oman,57.229600,19.89690,72575.92,2019-09-24,2019-09-29,0,10,Tropical Storm Hikaa,1.5,82.00,74.0,82.0,SSW,17.00,25.0,30.00,0.0,Partly cloudy
4913,4804,Ivory Coast,-4.010530,5.82018,34664.28,2019-10-04,2019-10-12,2,120,Heavy Rain,1.5,78.00,73.0,88.0,SSW,9.00,13.0,30.00,0.0,Patchy rain possible
4914,4807,Sudan,25.360000,14.08600,148559.72,2019-10-04,2019-10-07,0,1600,Torrential Rain,1.0,85.00,60.0,44.0,E,8.00,11.0,30.00,0.0,Patchy rain possible
4915,4808,Senegal,-15.516300,15.52020,60942.37,2019-09-10,2019-09-20,0,4500,Heavy Rain,1.0,87.00,72.0,79.0,W,10.00,15.0,30.00,0.0,Patchy rain possible
4916,4809,Venezuela,-72.228400,9.77189,24680.90,2019-10-05,2019-10-15,6,2000,Heavy Rain,1.5,88.00,76.0,82.0,SE,6.00,10.0,30.00,0.0,Patchy light rain with thunder
4917,4810,Mexico,-96.563600,16.08140,9327.84,2019-09-27,2019-10-05,2,500,Tropical Storm Narda,1.5,82.00,72.0,88.0,WNW,4.00,8.0,30.00,0.0,Partly cloudy
4918,4814,Tanzania,36.865700,-5.45658,113250.01,2019-10-12,2019-12-06,29,0,Heavy Rain,1.5,76.00,61.0,75.0,ESE,8.00,11.0,30.00,0.0,Partly cloudy
4919,4817,Togo,1.754700,8.06093,64158.06,2019-10-23,2019-11-06,0,0,Heavy Rain,1.5,82.00,74.0,96.0,SW,2.00,3.0,30.00,0.1,Moderate or heavy rain shower
4920,4819,Ghana,0.146375,5.81812,7285.63,2019-10-25,2019-10-30,0,0,Heavy Rain,1.0,82.00,75.0,84.0,WSW,7.00,10.0,30.00,0.0,Partly cloudy
4921,4824,Austria,12.864500,47.21650,16413.21,2019-11-15,2019-11-19,1,60,Heavy Rain,1.0,28.00,15.0,86.0,S,6.00,12.0,30.00,0.0,Partly cloudy
4922,4825,Democratic Republic of the Congo,23.232100,2.83151,678566.71,2019-11-01,2019-12-06,0,98000,Heavy Rain,1.5,76.00,71.0,98.0,SE,3.00,5.0,30.00,0.0,Light rain shower
4923,4829,Uganda,33.352100,2.39222,78161.92,2019-11-15,2019-12-06,4,1000,Heavy Rain,1.5,76.00,63.0,86.0,WNW,2.00,4.0,30.00,0.0,Patchy rain possible
4924,4844,Rwanda,29.925200,-2.00690,17894.83,2019-12-24,2019-12-26,12,550,Torrential Rain,2.0,74.00,60.0,94.0,NNW,2.00,4.0,30.00,0.0,Mist
4925,4872,Mozambique,35.282100,-18.01320,172916.51,2020-02-12,2020-02-17,2,2000,Heavy Rain,1.5,81.00,72.0,97.0,ENE,1.00,2.0,30.00,0.0,Patchy rain possible

In [181]:
df1.dtypes

ID                 int64
Country           object
long             float64
lat              float64
Area             float64
Began             object
Ended             object
Dead               int64
Displaced          int64
MainCause         object
Severity         float64
Temperature      float64
Dew Point        float64
Humidity         float64
Wind              object
Wind Speed       float64
Wind Gust        float64
Pressure         float64
Precipitation    float64
Condition         object
dtype: object

In [182]:
df1.columns =['ID','Country','longitude','latitude','Area','Began','Ended','Dead','Displaced','MainCause','Severity','Day-1_Temperature','Day-1_Dew_Point','Day-1_Humidity','Day-1_Wind','Day-1_Wind_Speed','Day-1_Wind_Gust','Day-1_Pressure','Day-1_Precipitation','Day-1_Condition']

In [183]:
df1.dtypes

ID                       int64
Country                 object
longitude              float64
latitude               float64
Area                   float64
Began                   object
Ended                   object
Dead                     int64
Displaced                int64
MainCause               object
Severity               float64
Day-1_Temperature      float64
Day-1_Dew_Point        float64
Day-1_Humidity         float64
Day-1_Wind              object
Day-1_Wind_Speed       float64
Day-1_Wind_Gust        float64
Day-1_Pressure         float64
Day-1_Precipitation    float64
Day-1_Condition         object
dtype: object

In [184]:
#read day minus 2 data
df2 = pd.read_csv("D:\Research Project\Datasets\Flood intensity\data url\Day minus 2 file\dayminus2 4926 not null rows processed.csv")
print(len(df2)) ####4926
df2.head()

4926

,Unnamed: 0,Unnamed: 0.1,ID,GlideNumber,Country,OtherCountry,long,lat,Area,Began,...,Time,Temperature,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Precipitation,Condition
0,0,0,1,0,Algeria,0,5.23026,35.81420,92615.67,1985-01-01,...,1594907477,84.20,NaN,28.0,NaN,3.60,NaN,30.12,NaN,Clouds
1,1,1,2,0,Brazil,0,-45.34890,-18.71110,678498.82,1985-01-15,...,1594907482,76.82,NaN,47.0,NaN,2.45,NaN,30.18,NaN,Clear
2,2,2,3,0,Phillipines,0,122.97400,10.02070,12846.03,1985-01-20,...,1594907482,69.42,NaN,100.0,NaN,1.74,NaN,29.80,NaN,Clouds
3,3,3,4,0,Indonesia,0,124.60600,1.01489,16542.12,1985-02-04,...,1594907482,75.20,NaN,94.0,NaN,0.50,NaN,29.83,NaN,Clouds
4,4,4,5,0,Mozambique,0,32.34910,-25.86930,20082.21,1985-02-09,...,1594907482,70.30,NaN,43.0,NaN,4.10,NaN,30.53,NaN,Clouds

In [185]:
#drop unrequired columns
df2.drop(df2.columns[[0,1,3,5,11,16,17,18]], axis=1, inplace=True)
df2

,ID,Country,long,lat,Area,Began,Ended,Dead,Displaced,MainCause,Severity,Temperature,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Precipitation,Condition
0,1,Algeria,5.230260,35.814200,92615.67,1985-01-01,1985-01-05,26,3000,Heavy rain,1.0,84.20,NaN,28.0,NaN,3.60,NaN,30.12,NaN,Clouds
1,2,Brazil,-45.348900,-18.711100,678498.82,1985-01-15,1985-02-02,229,80000,Heavy rain,2.0,76.82,NaN,47.0,NaN,2.45,NaN,30.18,NaN,Clear
2,3,Phillipines,122.974000,10.020700,12846.03,1985-01-20,1985-01-21,43,444,Torrential rain,1.0,69.42,NaN,100.0,NaN,1.74,NaN,29.80,NaN,Clouds
3,4,Indonesia,124.606000,1.014890,16542.12,1985-02-04,1985-02-18,21,300,Torrential rain,1.0,75.20,NaN,94.0,NaN,0.50,NaN,29.83,NaN,Clouds
4,5,Mozambique,32.349100,-25.869300,20082.21,1985-02-09,1985-02-11,19,0,Heavy rain,2.0,70.30,NaN,43.0,NaN,4.10,NaN,30.53,NaN,Clouds
5,6,Comoros islands,43.360000,-11.651600,1035.61,1985-02-16,1985-02-28,2,35000,Tropical cyclone,1.0,78.80,NaN,69.0,NaN,11.30,NaN,29.97,NaN,Clouds
6,7,New Zealand,175.734000,-37.230500,7871.37,1985-02-17,1985-02-18,4,200,Heavy rain,1.0,51.01,NaN,86.0,NaN,0.45,NaN,29.94,NaN,Rain
7,8,Indonesia,108.140000,-7.040080,77091.11,1985-02-19,1985-02-23,10,2000,Heavy rain,1.0,57.47,NaN,100.0,NaN,0.24,NaN,29.83,NaN,Clouds
8,10,Bolivia,-63.288700,-21.224400,69706.89,1985-02-25,1985-02-28,2,1000,Heavy Rain,1.0,69.94,NaN,38.0,NaN,1.73,NaN,30.00,NaN,Clouds
9,13,USA,-96.784500,29.604400,141508.00,1985-03-14,1985-03-15,0,0,Heavy rain,1.0,80.64,NaN,94.0,NaN,0.91,NaN,30.09,NaN,Clear
10,15,Brazil,-48.098700,-4.135190,1970402.21,1985-04-02,1985-04-17,32,700000,Heavy rain,2.0,87.10,NaN,50.0,NaN,2.65,NaN,29.94,NaN,Clear
11,17,China,127.897000,48.091700,300325.08,1985-04-21,1985-04-29,0,200,Ice jam/break-up,1.0,70.81,NaN,81.0,NaN,2.97,NaN,29.59,NaN,Clouds
12,20,USA,-66.706000,18.229100,1423.92,1985-05-19,1985-05-20,2,4500,Heavy rain,1.0,83.14,NaN,71.0,NaN,1.34,NaN,28.32,NaN,Clear
13,21,China,109.570000,25.669400,458666.21,1985-05-26,1985-06-06,64,10000,Heavy rain,2.0,82.40,NaN,78.0,NaN,2.00,NaN,29.65,NaN,Clouds
14,22,Argentina,-58.973500,-35.439200,78653.41,1985-05-30,1985-06-01,25,100000,Heavy rain,2.0,49.96,NaN,62.0,NaN,3.10,NaN,30.18,NaN,Clouds
15,23,Bangladesh,91.854200,24.649700,8910.30,1985-06-03,1985-06-22,7,100000,Heavy rain,2.0,81.57,NaN,88.0,NaN,3.14,NaN,29.62,NaN,Rain
16,26,Philippines,120.916000,14.741700,7768.19,1985-06-22,1985-06-30,98,130000,Tropical cyclone,1.0,86.56,NaN,71.0,NaN,3.40,NaN,29.80,NaN,Clouds
17,27,India,75.093700,14.539800,254234.60,1985-06-23,1985-06-27,95,25000,Heavy rain,1.0,72.63,NaN,92.0,NaN,5.27,NaN,29.65,NaN,Rain
18,28,China,109.974000,27.788200,290679.68,1985-06-28,1985-07-10,275,60000,Heavy rain,2.0,80.51,NaN,74.0,NaN,2.03,NaN,29.62,NaN,Clouds
19,29,Bangladesh,89.985300,22.617600,6446.85,1985-07-03,1985-07-04,2,77000,Heavy rain,1.0,84.20,NaN,77.0,NaN,3.46,NaN,29.56,NaN,Clouds
20,30,West Germany,6.509520,50.713400,1927.64,1985-07-06,1985-07-07,3,0,Heavy rain,1.0,60.98,NaN,88.0,NaN,3.60,NaN,30.03,NaN,Drizzle
21,32,Chad,21.550900,11.672700,15243.93,1985-07-13,1985-07-16,0,1600,Heavy rain,1.0,78.58,NaN,77.0,NaN,1.94,NaN,29.83,NaN,Clouds
22,33,India,76.910300,32.835300,117441.17,1985-07-18,1985-07-30,340,20000,Heavy rain,1.0,40.60,NaN,82.0,NaN,2.12,NaN,29.71,NaN,Clouds
23,34,Sudan,24.913900,13.489000,63577.12,1985-07-19,1985-07-22,0,0,Heavy rain,1.0,91.13,NaN,30.0,NaN,6.77,NaN,29.77,NaN,Clouds
24,35,China,125.156000,42.695300,994498.21,1985-07-20,1985-09-02,200,2000000,Tropical cyclone,2.0,72.07,NaN,71.0,NaN,3.39,NaN,29.71,NaN,Clouds
25,36,Bangladesh,90.199900,23.102800,5663.46,1985-07-21,1985-08-17,15,175000,Heavy rain,1.0,83.57,NaN,80.0,NaN,3.72,NaN,29.56,NaN,Clouds
26,38,China,120.376000,31.511200,58279.12,1985-08-01,1985-08-02,3,200000,Heavy rain,1.0,75.34,NaN,71.0,NaN,0.45,NaN,29.56,NaN,Clouds
27,40,Nepal,87.125800,27.504900,12487.89,1985-08-04,1985-08-05,3,160,Heavy Rain,2.0,69.24,NaN,83.0,NaN,0.21,NaN,29.71,NaN,Rain
28,41,China,100.797000,23.525500,146691.46,1985-08-06,1985-08-09,283,14000,Heavy rain,1.0,65.61,NaN,96.0,NaN,0.95,NaN,29.71,NaN,Clouds
29,42,Austria,12.206600,47.315500,15151.05,1985-08-07,1985-08-08,12,0,Heavy rain,2.0,61.00,NaN,89.0,NaN,2.61,NaN,30.09,NaN,Rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4896,4874,Burundi,29.987000,-3.407660,17373.89,2020-02-07,2020-02-17,3,1000,Heavy Rain,1.5,66.00,62.0,97.0,WSW,2.00,3.0,30.00,0.2,Heavy rain at times
4897,4875,Tanzania,35.282100,-7.773570,266334.32,2020-02-01,2020-02-17,40,15000,Heavy Rain,2.0,68.00,60.0,96.0,ESE,2.00,4.0,30.00,0.0,Patchy rain possible
4898,4879,Pakistan,71.036500,33.302600,116828.75,2020-03-06,2020-03-17,33,1200,Heavy Rain,1.5,60.00,44.0,55.0,WSW,2.00,5.0,30.00,0.0,Light rain shower
4899,4882,Zambia,29.962300,-10.250400,101083.20,2020-03-04,2020-03-17,0,0,Heavy Rain,1.5,69.00,60.0,97.0,E,3.00,5.0,30.00,0.0,Fog
4900,4884,Burundi,30.086000,-3.085660,13769.59,2020-03-02,2020-03-08,1,185,Heavy Rain,1.5,73.00,60.0,96.0,SW,2.00,5.0,30.00,0.0,Mist
4901,4885,Rwanda,29.863300,-1.994450,15283.09,2020-03-02,2020-03-05,10,0,Heavy Rain,1.5,76.00,60.0,97.0,NW,1.00,1.0,30.00,0.0,Fog
4902,4888,Vietnam,105.183000,20.691000,50183.18,2020-03-02,2020-03-10,2,1000,Heavy Rain,1.0,79.00,66.0,86.0,S,4.00,4.0,30.00,0.0,Partly cloudy
4903,4891,Spain,-0.101059,40.132000,4269.15,2020-04-01,2020-04-02,0,91,Torrential Rain,1.5,52.00,44.0,62.0,W,1.00,2.0,30.00,0.0,Partly cloudy
4904,4892,Papua New Guinea,146.752000,-6.925130,14567.65,2020-04-01,2020-04-03,0,0,Heavy Rain,1.0,84.00,73.0,88.0,WSW,2.00,3.0,30.00,0.1,Light rain shower
4905,4894,Afghanistan,65.642400,33.826000,220551.72,2020-03-21,2020-04-03,11,1200,Heavy Rain,1.5,45.00,27.0,61.0,SE,4.00,5.0,31.00,0.0,Partly cloudy
4906,4895,Zambia,30.902500,-10.090100,91521.53,2020-03-04,2020-04-24,0,0,Heavy Rain,1.5,70.00,61.0,97.0,WNW,4.00,6.0,30.00,0.1,Moderate rain at times
4907,4896,Democratic Republic of Congo,26.745600,-3.244940,180311.71,2020-03-17,2020-04-03,36,78000,Heavy Rain,2.0,84.00,69.0,94.0,SSE,2.00,4.0,30.00,0.0,Mist
4908,4897,Kenya,36.593500,1.163430,154389.90,2020-03-27,2020-04-27,1,3000,Heavy Rain,1.5,71.00,57.0,81.0,NNE,2.00,3.0,30.00,0.0,Patchy rain possible
4909,4898,Peru,-76.880100,-7.010730,152175.01,2020-03-28,2020-04-02,0,120,Heavy Rain,1.5,85.00,70.0,90.0,W,2.00,4.0,30.00,0.0,Patchy rain possible
4910,4900,Tanzania,34.218200,-4.512360,184333.48,2020-04-24,2020-04-27,2,10000,Heavy Rain,1.5,70.00,64.0,95.0,ENE,1.00,2.0,30.00,0.0,Patchy rain possible
4911,4901,Djibouti,42.680400,11.685100,10321.78,2020-04-21,2020-04-26,8,0,Torrential Rain,2.0,84.00,77.0,83.0,E,9.00,12.0,30.00,0.0,Thundery outbreaks possible
4912,4902,Burkina Faso,-1.115540,13.343200,42577.65,2020-04-19,2020-04-26,0,2000,Torrential Rain,1.5,100.00,17.0,7.0,NE,9.00,18.0,30.00,0.0,Partly cloudy
4913,4903,Burundi,29.937500,-2.763120,41569.31,2020-04-19,2020-04-26,9,0,Heavy Rain,1.5,69.00,61.0,95.0,WSW,2.00,5.0,30.00,0.1,Moderate or heavy rain shower
4914,4905,Vietnam,106.172000,17.888600,15289.41,2020-04-22,2020-04-26,3,0,Torrential Rain,1.0,86.00,73.0,85.0,SE,4.00,7.0,30.00,0.0,Partly cloudy
4915,4906,Angola,14.200700,-9.139080,77631.98,2020-04-18,2020-04-24,11,90,Heavy Rain,1.5,77.00,71.0,100.0,W,3.00,5.0,30.00,0.1,Light rain shower
4916,4907,New Caledonia,165.854000,-21.488300,8299.71,2020-04-18,2020-04-22,0,0,Torrential Rain,1.0,77.00,70.0,84.0,SE,10.00,13.0,30.00,0.0,Patchy rain possible
4917,4912,Chad,18.085400,9.627940,134488.38,2020-04-20,2020-04-26,0,2062,Heavy Rain,1.0,100.00,38.0,17.0,SE,3.00,6.0,30.00,0.0,Partly cloudy
4918,4913,Uzbekistan,55.844000,41.245100,84662.22,2020-05-01,2020-05-11,4,70000,Dam break,2.0,66.00,38.0,37.0,WNW,9.00,15.0,30.00,0.0,Partly cloudy
4919,4914,Sri Lanka,80.859700,7.835490,46625.90,2020-05-17,2020-05-20,2,1100,Tropical Storm Amphan,1.5,84.00,75.0,94.0,WSW,6.00,11.0,30.00,0.0,Mist
4920,4916,Democratic Republic Congo,17.615300,-3.822620,84572.69,2020-05-16,2020-05-20,0,500,Heavy Rain,1.5,82.00,71.0,91.0,WSW,1.00,3.0,30.00,0.0,Patchy rain possible
4921,4917,Algeria,12.666600,31.683700,91355.80,2020-05-16,2020-05-18,1,0,Heavy Rain,1.0,99.00,22.0,8.0,SSE,20.00,34.0,30.00,0.0,Partly cloudy
4922,4918,Ecuador,-77.993600,-2.683770,24825.78,2020-05-16,2020-05-19,2,15,Heavy Rain,1.0,50.00,51.0,85.0,ESE,2.00,4.0,30.00,0.1,Heavy rain at times
4923,4924,Cental African Republic,17.021400,4.582310,65353.26,2020-05-24,2020-05-30,3,0,Torrential Rain,1.0,78.00,67.0,95.0,SW,6.00,11.0,30.00,0.0,Mist
4924,4925,Uganda,31.026300,0.013018,47454.12,2020-05-21,2020-05-25,8,300,Torrential Rain,1.5,70.00,62.0,95.0,SSW,2.00,4.0,30.00,0.0,Patchy rain possible
4925,4928,El Salvador,-89.623000,17.391100,253817.46,2020-06-02,2020-06-03,0,0,Tropical Storm Cristobal,1.5,73.00,71.0,99.0,ENE,6.00,11.0,30.00,0.3,Heavy rain

In [187]:
df2.dtypes

ID                 int64
Country           object
long             float64
lat              float64
Area             float64
Began             object
Ended             object
Dead               int64
Displaced          int64
MainCause         object
Severity         float64
Temperature      float64
Dew Point        float64
Humidity         float64
Wind              object
Wind Speed       float64
Wind Gust        float64
Pressure         float64
Precipitation    float64
Condition         object
dtype: object

In [188]:
df2.columns =['ID','Country','longitude','latitude','Area','Began','Ended','Dead','Displaced','MainCause','Severity','Day-2_Temperature','Day-2_Dew_Point','Day-2_Humidity','Day-2_Wind','Day-2_Wind_Speed','Day-2_Wind_Gust','Day-2_Pressure','Day-2_Precipitation','Day-2_Condition']

In [189]:
df2.dtypes

ID                       int64
Country                 object
longitude              float64
latitude               float64
Area                   float64
Began                   object
Ended                   object
Dead                     int64
Displaced                int64
MainCause               object
Severity               float64
Day-2_Temperature      float64
Day-2_Dew_Point        float64
Day-2_Humidity         float64
Day-2_Wind              object
Day-2_Wind_Speed       float64
Day-2_Wind_Gust        float64
Day-2_Pressure         float64
Day-2_Precipitation    float64
Day-2_Condition         object
dtype: object

In [190]:
#read day minus 3 data
df3 = pd.read_csv("D:\Research Project\Datasets\Flood intensity\data url\Day minus 3 file\dayminus3 4926 not null rows processed.csv")
print(len(df3)) ####4926
df3.head()

4926

,Unnamed: 0,Unnamed: 0.1,ID,GlideNumber,Country,OtherCountry,long,lat,Area,Began,...,Time,Temperature,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Precipitation,Condition
0,0,0,1,0,Algeria,0,5.23026,35.81420,92615.67,1985-01-01,...,1594842325,73.40,NaN,60.0,NaN,3.60,NaN,30.12,NaN,Clouds
1,1,1,2,0,Brazil,0,-45.34890,-18.71110,678498.82,1985-01-15,...,1594842330,81.27,NaN,36.0,NaN,1.94,NaN,30.00,NaN,Clouds
2,2,2,3,0,Phillipines,0,122.97400,10.02070,12846.03,1985-01-20,...,1594842330,67.64,NaN,100.0,NaN,1.38,NaN,29.77,NaN,Rain
3,3,3,4,0,Indonesia,0,124.60600,1.01489,16542.12,1985-02-04,...,1594842331,75.20,NaN,94.0,NaN,1.00,NaN,29.80,NaN,Clouds
4,4,4,5,0,Mozambique,0,32.34910,-25.86930,20082.21,1985-02-09,...,1594842331,62.29,NaN,48.0,NaN,6.70,NaN,30.59,NaN,Clear

In [191]:
#drop unrequired columns
df3.drop(df3.columns[[0,1,3,5,11,16,17,18]], axis=1, inplace=True)
df3

,ID,Country,long,lat,Area,Began,Ended,Dead,Displaced,MainCause,Severity,Temperature,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Precipitation,Condition
0,1,Algeria,5.230260,35.814200,92615.67,1985-01-01,1985-01-05,26,3000,Heavy rain,1.0,73.40,NaN,60.0,NaN,3.60,NaN,30.12,NaN,Clouds
1,2,Brazil,-45.348900,-18.711100,678498.82,1985-01-15,1985-02-02,229,80000,Heavy rain,2.0,81.27,NaN,36.0,NaN,1.94,NaN,30.00,NaN,Clouds
2,3,Phillipines,122.974000,10.020700,12846.03,1985-01-20,1985-01-21,43,444,Torrential rain,1.0,67.64,NaN,100.0,NaN,1.38,NaN,29.77,NaN,Rain
3,4,Indonesia,124.606000,1.014890,16542.12,1985-02-04,1985-02-18,21,300,Torrential rain,1.0,75.20,NaN,94.0,NaN,1.00,NaN,29.80,NaN,Clouds
4,5,Mozambique,32.349100,-25.869300,20082.21,1985-02-09,1985-02-11,19,0,Heavy rain,2.0,62.29,NaN,48.0,NaN,6.70,NaN,30.59,NaN,Clear
5,6,Comoros islands,43.360000,-11.651600,1035.61,1985-02-16,1985-02-28,2,35000,Tropical cyclone,1.0,68.85,NaN,84.0,NaN,7.23,NaN,30.12,NaN,Rain
6,7,New Zealand,175.734000,-37.230500,7871.37,1985-02-17,1985-02-18,4,200,Heavy rain,1.0,53.01,NaN,88.0,NaN,9.39,NaN,30.00,NaN,Rain
7,8,Indonesia,108.140000,-7.040080,77091.11,1985-02-19,1985-02-23,10,2000,Heavy rain,1.0,57.16,NaN,100.0,NaN,1.01,NaN,29.80,NaN,Clouds
8,10,Bolivia,-63.288700,-21.224400,69706.89,1985-02-25,1985-02-28,2,1000,Heavy Rain,1.0,76.01,NaN,37.0,NaN,3.12,NaN,29.83,NaN,Clear
9,13,USA,-96.784500,29.604400,141508.00,1985-03-14,1985-03-15,0,0,Heavy rain,1.0,96.75,NaN,47.0,NaN,5.10,NaN,30.00,NaN,Clouds
10,15,Brazil,-48.098700,-4.135190,1970402.21,1985-04-02,1985-04-17,32,700000,Heavy rain,2.0,87.93,NaN,49.0,NaN,1.54,NaN,29.80,NaN,Clouds
11,17,China,127.897000,48.091700,300325.08,1985-04-21,1985-04-29,0,200,Ice jam/break-up,1.0,64.60,NaN,95.0,NaN,1.97,NaN,29.59,NaN,Clear
12,20,USA,-66.706000,18.229100,1423.92,1985-05-19,1985-05-20,2,4500,Heavy rain,1.0,81.79,NaN,66.0,NaN,1.79,NaN,28.26,NaN,Rain
13,21,China,109.570000,25.669400,458666.21,1985-05-26,1985-06-06,64,10000,Heavy rain,2.0,78.80,NaN,94.0,NaN,1.29,NaN,29.68,NaN,Clouds
14,22,Argentina,-58.973500,-35.439200,78653.41,1985-05-30,1985-06-01,25,100000,Heavy rain,2.0,53.10,NaN,55.0,NaN,2.59,NaN,30.18,NaN,Clear
15,23,Bangladesh,91.854200,24.649700,8910.30,1985-06-03,1985-06-22,7,100000,Heavy rain,2.0,77.88,NaN,93.0,NaN,2.10,NaN,29.68,NaN,Rain
16,26,Philippines,120.916000,14.741700,7768.19,1985-06-22,1985-06-30,98,130000,Tropical cyclone,1.0,81.00,NaN,83.0,NaN,2.05,NaN,29.80,NaN,Rain
17,27,India,75.093700,14.539800,254234.60,1985-06-23,1985-06-27,95,25000,Heavy rain,1.0,70.30,NaN,95.0,NaN,4.16,NaN,29.68,NaN,Rain
18,28,China,109.974000,27.788200,290679.68,1985-06-28,1985-07-10,275,60000,Heavy rain,2.0,74.21,NaN,96.0,NaN,1.03,NaN,29.65,NaN,Clouds
19,29,Bangladesh,89.985300,22.617600,6446.85,1985-07-03,1985-07-04,2,77000,Heavy rain,1.0,81.07,NaN,86.0,NaN,2.24,NaN,29.62,NaN,Clouds
20,30,West Germany,6.509520,50.713400,1927.64,1985-07-06,1985-07-07,3,0,Heavy rain,1.0,63.10,NaN,48.0,NaN,1.50,NaN,29.97,NaN,Clouds
21,32,Chad,21.550900,11.672700,15243.93,1985-07-13,1985-07-16,0,1600,Heavy rain,1.0,78.17,NaN,76.0,NaN,1.73,NaN,29.88,NaN,Rain
22,33,India,76.910300,32.835300,117441.17,1985-07-18,1985-07-30,340,20000,Heavy rain,1.0,33.89,NaN,99.0,NaN,0.29,NaN,29.85,NaN,Clouds
23,34,Sudan,24.913900,13.489000,63577.12,1985-07-19,1985-07-22,0,0,Heavy rain,1.0,78.06,NaN,61.0,NaN,6.31,NaN,29.88,NaN,Rain
24,35,China,125.156000,42.695300,994498.21,1985-07-20,1985-09-02,200,2000000,Tropical cyclone,2.0,65.95,NaN,77.0,NaN,2.88,NaN,29.68,NaN,Clear
25,36,Bangladesh,90.199900,23.102800,5663.46,1985-07-21,1985-08-17,15,175000,Heavy rain,1.0,79.95,NaN,90.0,NaN,2.58,NaN,29.62,NaN,Clouds
26,38,China,120.376000,31.511200,58279.12,1985-08-01,1985-08-02,3,200000,Heavy rain,1.0,71.83,NaN,80.0,NaN,0.45,NaN,29.50,NaN,Rain
27,40,Nepal,87.125800,27.504900,12487.89,1985-08-04,1985-08-05,3,160,Heavy Rain,2.0,67.51,NaN,81.0,NaN,0.49,NaN,29.83,NaN,Rain
28,41,China,100.797000,23.525500,146691.46,1985-08-06,1985-08-09,283,14000,Heavy rain,1.0,63.00,NaN,96.0,NaN,0.65,NaN,29.74,NaN,Rain
29,42,Austria,12.206600,47.315500,15151.05,1985-08-07,1985-08-08,12,0,Heavy rain,2.0,55.98,NaN,95.0,NaN,1.10,NaN,29.94,NaN,Rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4896,4874,Burundi,29.987000,-3.407660,17373.89,2020-02-07,2020-02-17,3,1000,Heavy Rain,1.5,70.00,62.0,95.0,NW,2.00,3.0,30.00,0.0,Moderate rain at times
4897,4875,Tanzania,35.282100,-7.773570,266334.32,2020-02-01,2020-02-17,40,15000,Heavy Rain,2.0,65.00,60.0,96.0,SSW,1.00,2.0,30.00,0.0,Mist
4898,4879,Pakistan,71.036500,33.302600,116828.75,2020-03-06,2020-03-17,33,1200,Heavy Rain,1.5,72.00,44.0,56.0,NW,1.00,2.0,30.00,0.0,Partly cloudy
4899,4882,Zambia,29.962300,-10.250400,101083.20,2020-03-04,2020-03-17,0,0,Heavy Rain,1.5,65.00,63.0,97.0,SSE,5.00,10.0,30.00,0.0,Light rain shower
4900,4884,Burundi,30.086000,-3.085660,13769.59,2020-03-02,2020-03-08,1,185,Heavy Rain,1.5,65.00,61.0,92.0,SSW,2.00,4.0,30.00,0.0,Patchy rain possible
4901,4885,Rwanda,29.863300,-1.994450,15283.09,2020-03-02,2020-03-05,10,0,Heavy Rain,1.5,69.00,62.0,94.0,WNW,2.00,4.0,30.00,0.0,Mist
4902,4888,Vietnam,105.183000,20.691000,50183.18,2020-03-02,2020-03-10,2,1000,Heavy Rain,1.0,79.00,68.0,88.0,SSE,4.00,4.0,30.00,0.0,Partly cloudy
4903,4891,Spain,-0.101059,40.132000,4269.15,2020-04-01,2020-04-02,0,91,Torrential Rain,1.5,61.00,41.0,65.0,WNW,4.00,8.0,31.00,0.0,Partly cloudy
4904,4892,Papua New Guinea,146.752000,-6.925130,14567.65,2020-04-01,2020-04-03,0,0,Heavy Rain,1.0,83.00,73.0,81.0,W,4.00,6.0,30.00,0.0,Partly cloudy
4905,4894,Afghanistan,65.642400,33.826000,220551.72,2020-03-21,2020-04-03,11,1200,Heavy Rain,1.5,44.00,29.0,74.0,ESE,4.00,5.0,31.00,0.0,Partly cloudy
4906,4895,Zambia,30.902500,-10.090100,91521.53,2020-03-04,2020-04-24,0,0,Heavy Rain,1.5,68.00,64.0,96.0,S,3.00,5.0,30.00,0.1,Moderate or heavy rain shower
4907,4896,Democratic Republic of Congo,26.745600,-3.244940,180311.71,2020-03-17,2020-04-03,36,78000,Heavy Rain,2.0,80.00,68.0,99.0,E,3.00,5.0,30.00,0.0,Fog
4908,4897,Kenya,36.593500,1.163430,154389.90,2020-03-27,2020-04-27,1,3000,Heavy Rain,1.5,71.00,53.0,72.0,NE,2.00,3.0,30.00,0.0,Patchy rain possible
4909,4898,Peru,-76.880100,-7.010730,152175.01,2020-03-28,2020-04-02,0,120,Heavy Rain,1.5,84.00,70.0,98.0,WSW,1.00,2.0,30.00,0.0,Patchy rain possible
4910,4900,Tanzania,34.218200,-4.512360,184333.48,2020-04-24,2020-04-27,2,10000,Heavy Rain,1.5,69.00,64.0,94.0,ESE,2.00,5.0,30.00,0.1,Moderate or heavy rain shower
4911,4901,Djibouti,42.680400,11.685100,10321.78,2020-04-21,2020-04-26,8,0,Torrential Rain,2.0,85.00,75.0,81.0,ESE,9.00,13.0,30.00,0.0,Cloudy
4912,4902,Burkina Faso,-1.115540,13.343200,42577.65,2020-04-19,2020-04-26,0,2000,Torrential Rain,1.5,97.00,53.0,35.0,N,19.00,26.0,30.00,0.0,Partly cloudy
4913,4903,Burundi,29.937500,-2.763120,41569.31,2020-04-19,2020-04-26,9,0,Heavy Rain,1.5,72.00,59.0,95.0,W,2.00,5.0,30.00,0.0,Mist
4914,4905,Vietnam,106.172000,17.888600,15289.41,2020-04-22,2020-04-26,3,0,Torrential Rain,1.0,86.00,72.0,87.0,SSE,4.00,7.0,30.00,0.0,Partly cloudy
4915,4906,Angola,14.200700,-9.139080,77631.98,2020-04-18,2020-04-24,11,90,Heavy Rain,1.5,79.00,69.0,97.0,NW,1.00,3.0,30.00,0.1,Moderate or heavy rain shower
4916,4907,New Caledonia,165.854000,-21.488300,8299.71,2020-04-18,2020-04-22,0,0,Torrential Rain,1.0,77.00,71.0,85.0,ESE,12.00,16.0,31.00,0.0,Patchy rain possible
4917,4912,Chad,18.085400,9.627940,134488.38,2020-04-20,2020-04-26,0,2062,Heavy Rain,1.0,100.00,31.0,13.0,SSE,1.00,3.0,30.00,0.0,Clear
4918,4913,Uzbekistan,55.844000,41.245100,84662.22,2020-05-01,2020-05-11,4,70000,Dam break,2.0,64.00,42.0,53.0,W,17.00,24.0,30.00,0.0,Partly cloudy
4919,4914,Sri Lanka,80.859700,7.835490,46625.90,2020-05-17,2020-05-20,2,1100,Tropical Storm Amphan,1.5,84.00,74.0,93.0,SE,2.00,4.0,30.00,0.0,Partly cloudy
4920,4916,Democratic Republic Congo,17.615300,-3.822620,84572.69,2020-05-16,2020-05-20,0,500,Heavy Rain,1.5,80.00,72.0,96.0,WNW,2.00,4.0,30.00,0.0,Mist
4921,4917,Algeria,12.666600,31.683700,91355.80,2020-05-16,2020-05-18,1,0,Heavy Rain,1.0,96.00,41.0,22.0,SE,20.00,34.0,30.00,0.0,Cloudy
4922,4918,Ecuador,-77.993600,-2.683770,24825.78,2020-05-16,2020-05-19,2,15,Heavy Rain,1.0,51.00,53.0,88.0,SW,3.00,6.0,30.00,0.2,Torrential rain shower
4923,4924,Cental African Republic,17.021400,4.582310,65353.26,2020-05-24,2020-05-30,3,0,Torrential Rain,1.0,75.00,68.0,92.0,WSW,4.00,8.0,30.00,0.0,Patchy rain possible
4924,4925,Uganda,31.026300,0.013018,47454.12,2020-05-21,2020-05-25,8,300,Torrential Rain,1.5,70.00,61.0,94.0,SW,3.00,5.0,30.00,0.0,Light rain shower
4925,4928,El Salvador,-89.623000,17.391100,253817.46,2020-06-02,2020-06-03,0,0,Tropical Storm Cristobal,1.5,77.00,72.0,97.0,E,3.00,7.0,30.00,0.2,Moderate or heavy rain shower

In [192]:
df3.dtypes

ID                 int64
Country           object
long             float64
lat              float64
Area             float64
Began             object
Ended             object
Dead               int64
Displaced          int64
MainCause         object
Severity         float64
Temperature      float64
Dew Point        float64
Humidity         float64
Wind              object
Wind Speed       float64
Wind Gust        float64
Pressure         float64
Precipitation    float64
Condition         object
dtype: object

In [193]:
df3.columns =['ID','Country','longitude','latitude','Area','Began','Ended','Dead','Displaced','MainCause','Severity','Day-3_Temperature','Day-3_Dew_Point','Day-3_Humidity','Day-3_Wind','Day-3_Wind_Speed','Day-3_Wind_Gust','Day-3_Pressure','Day-3_Precipitation','Day-3_Condition']

In [194]:
df3.dtypes

ID                       int64
Country                 object
longitude              float64
latitude               float64
Area                   float64
Began                   object
Ended                   object
Dead                     int64
Displaced                int64
MainCause               object
Severity               float64
Day-3_Temperature      float64
Day-3_Dew_Point        float64
Day-3_Humidity         float64
Day-3_Wind              object
Day-3_Wind_Speed       float64
Day-3_Wind_Gust        float64
Day-3_Pressure         float64
Day-3_Precipitation    float64
Day-3_Condition         object
dtype: object

In [195]:
#read day minus 3 data
df4 = pd.read_csv("D:\Research Project\Datasets\Flood intensity\data url\Day minus 4 file\dayminus4 4926 not null rows processed.csv")
print(len(df4)) ####4926
df4.head()

4926

,Unnamed: 0,Unnamed: 0.1,ID,GlideNumber,Country,OtherCountry,long,lat,Area,Began,...,Time,Temperature,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Precipitation,Condition
0,0,0,1,0,Algeria,0,5.23026,35.81420,92615.67,1985-01-01,...,1594865213,66.20,NaN,88.0,NaN,3.10,NaN,30.12,NaN,Clouds
1,1,1,2,0,Brazil,0,-45.34890,-18.71110,678498.82,1985-01-15,...,1594865218,69.51,NaN,61.0,NaN,1.73,NaN,30.12,NaN,Clouds
2,2,2,3,0,Phillipines,0,122.97400,10.02070,12846.03,1985-01-20,...,1594865218,75.85,NaN,85.0,NaN,1.93,NaN,29.80,NaN,Clouds
3,3,3,4,0,Indonesia,0,124.60600,1.01489,16542.12,1985-02-04,...,1594865219,87.80,NaN,58.0,NaN,1.00,NaN,29.83,NaN,Clouds
4,4,4,5,0,Mozambique,0,32.34910,-25.86930,20082.21,1985-02-09,...,1594865219,53.29,NaN,62.0,NaN,4.10,NaN,30.56,NaN,Clear

In [196]:
#drop unrequired columns
df4.drop(df4.columns[[0,1,3,5,11,16,17,18]], axis=1, inplace=True)
df4

,ID,Country,long,lat,Area,Began,Ended,Dead,Displaced,MainCause,Severity,Temperature,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Precipitation,Condition
0,1,Algeria,5.230260,35.814200,92615.67,1985-01-01,1985-01-05,26,3000,Heavy rain,1.0,66.20,NaN,88.0,NaN,3.10,NaN,30.12,NaN,Clouds
1,2,Brazil,-45.348900,-18.711100,678498.82,1985-01-15,1985-02-02,229,80000,Heavy rain,2.0,69.51,NaN,61.0,NaN,1.73,NaN,30.12,NaN,Clouds
2,3,Phillipines,122.974000,10.020700,12846.03,1985-01-20,1985-01-21,43,444,Torrential rain,1.0,75.85,NaN,85.0,NaN,1.93,NaN,29.80,NaN,Clouds
3,4,Indonesia,124.606000,1.014890,16542.12,1985-02-04,1985-02-18,21,300,Torrential rain,1.0,87.80,NaN,58.0,NaN,1.00,NaN,29.83,NaN,Clouds
4,5,Mozambique,32.349100,-25.869300,20082.21,1985-02-09,1985-02-11,19,0,Heavy rain,2.0,53.29,NaN,62.0,NaN,4.10,NaN,30.56,NaN,Clear
5,6,Comoros islands,43.360000,-11.651600,1035.61,1985-02-16,1985-02-28,2,35000,Tropical cyclone,1.0,67.95,NaN,87.0,NaN,9.03,NaN,30.03,NaN,Rain
6,7,New Zealand,175.734000,-37.230500,7871.37,1985-02-17,1985-02-18,4,200,Heavy rain,1.0,52.00,NaN,90.0,NaN,8.94,NaN,29.94,NaN,Rain
7,8,Indonesia,108.140000,-7.040080,77091.11,1985-02-19,1985-02-23,10,2000,Heavy rain,1.0,66.00,NaN,96.0,NaN,0.96,NaN,29.85,NaN,Clouds
8,10,Bolivia,-63.288700,-21.224400,69706.89,1985-02-25,1985-02-28,2,1000,Heavy Rain,1.0,61.66,NaN,50.0,NaN,0.91,NaN,29.94,NaN,Clouds
9,13,USA,-96.784500,29.604400,141508.00,1985-03-14,1985-03-15,0,0,Heavy rain,1.0,85.14,NaN,66.0,NaN,4.10,NaN,29.97,NaN,Clear
10,15,Brazil,-48.098700,-4.135190,1970402.21,1985-04-02,1985-04-17,32,700000,Heavy rain,2.0,73.06,NaN,77.0,NaN,1.21,NaN,29.91,NaN,Clear
11,17,China,127.897000,48.091700,300325.08,1985-04-21,1985-04-29,0,200,Ice jam/break-up,1.0,85.71,NaN,44.0,NaN,3.75,NaN,29.59,NaN,Clouds
12,20,USA,-66.706000,18.229100,1423.92,1985-05-19,1985-05-20,2,4500,Heavy rain,1.0,74.98,NaN,93.0,NaN,1.18,NaN,28.29,NaN,Rain
13,21,China,109.570000,25.669400,458666.21,1985-05-26,1985-06-06,64,10000,Heavy rain,2.0,86.00,NaN,66.0,NaN,6.00,NaN,29.71,NaN,Clouds
14,22,Argentina,-58.973500,-35.439200,78653.41,1985-05-30,1985-06-01,25,100000,Heavy rain,2.0,47.79,NaN,56.0,NaN,3.71,NaN,30.21,NaN,Clouds
15,23,Bangladesh,91.854200,24.649700,8910.30,1985-06-03,1985-06-22,7,100000,Heavy rain,2.0,83.19,NaN,82.0,NaN,2.31,NaN,29.68,NaN,Rain
16,26,Philippines,120.916000,14.741700,7768.19,1985-06-22,1985-06-30,98,130000,Tropical cyclone,1.0,88.00,NaN,72.0,NaN,0.89,NaN,29.77,NaN,Clouds
17,27,India,75.093700,14.539800,254234.60,1985-06-23,1985-06-27,95,25000,Heavy rain,1.0,70.41,NaN,92.0,NaN,3.69,NaN,29.68,NaN,Clouds
18,28,China,109.974000,27.788200,290679.68,1985-06-28,1985-07-10,275,60000,Heavy rain,2.0,86.04,NaN,67.0,NaN,3.67,NaN,29.65,NaN,Rain
19,29,Bangladesh,89.985300,22.617600,6446.85,1985-07-03,1985-07-04,2,77000,Heavy rain,1.0,85.93,NaN,72.0,NaN,2.72,NaN,29.62,NaN,Clouds
20,30,West Germany,6.509520,50.713400,1927.64,1985-07-06,1985-07-07,3,0,Heavy rain,1.0,58.10,NaN,93.0,NaN,1.50,NaN,30.00,NaN,Clouds
21,32,Chad,21.550900,11.672700,15243.93,1985-07-13,1985-07-16,0,1600,Heavy rain,1.0,70.23,NaN,86.0,NaN,4.36,NaN,29.91,NaN,Rain
22,33,India,76.910300,32.835300,117441.17,1985-07-18,1985-07-30,340,20000,Heavy rain,1.0,35.74,NaN,83.0,NaN,1.08,NaN,29.85,NaN,Clear
23,34,Sudan,24.913900,13.489000,63577.12,1985-07-19,1985-07-22,0,0,Heavy rain,1.0,78.13,NaN,52.0,NaN,2.78,NaN,29.85,NaN,Clouds
24,35,China,125.156000,42.695300,994498.21,1985-07-20,1985-09-02,200,2000000,Tropical cyclone,2.0,83.62,NaN,48.0,NaN,1.87,NaN,29.68,NaN,Clear
25,36,Bangladesh,90.199900,23.102800,5663.46,1985-07-21,1985-08-17,15,175000,Heavy rain,1.0,85.03,NaN,77.0,NaN,3.03,NaN,29.62,NaN,Clouds
26,38,China,120.376000,31.511200,58279.12,1985-08-01,1985-08-02,3,200000,Heavy rain,1.0,74.86,NaN,73.0,NaN,0.89,NaN,29.53,NaN,Rain
27,40,Nepal,87.125800,27.504900,12487.89,1985-08-04,1985-08-05,3,160,Heavy Rain,2.0,69.87,NaN,80.0,NaN,0.43,NaN,29.80,NaN,Rain
28,41,China,100.797000,23.525500,146691.46,1985-08-06,1985-08-09,283,14000,Heavy rain,1.0,69.42,NaN,90.0,NaN,1.42,NaN,29.77,NaN,Rain
29,42,Austria,12.206600,47.315500,15151.05,1985-08-07,1985-08-08,12,0,Heavy rain,2.0,53.55,NaN,97.0,NaN,0.67,NaN,29.94,NaN,Rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4896,4874,Burundi,29.987000,-3.407660,17373.89,2020-02-07,2020-02-17,3,1000,Heavy Rain,1.5,71.00,60.0,95.0,SSW,2.00,4.0,31.00,0.0,Patchy rain possible
4897,4875,Tanzania,35.282100,-7.773570,266334.32,2020-02-01,2020-02-17,40,15000,Heavy Rain,2.0,62.00,60.0,95.0,SE,1.00,1.0,30.00,0.0,Patchy rain possible
4898,4879,Pakistan,71.036500,33.302600,116828.75,2020-03-06,2020-03-17,33,1200,Heavy Rain,1.5,71.00,47.0,59.0,WNW,2.00,5.0,30.00,0.0,Partly cloudy
4899,4882,Zambia,29.962300,-10.250400,101083.20,2020-03-04,2020-03-17,0,0,Heavy Rain,1.5,74.00,63.0,98.0,NE,6.00,11.0,30.00,0.0,Light rain
4900,4884,Burundi,30.086000,-3.085660,13769.59,2020-03-02,2020-03-08,1,185,Heavy Rain,1.5,70.00,61.0,93.0,SW,2.00,4.0,30.00,0.0,Patchy rain possible
4901,4885,Rwanda,29.863300,-1.994450,15283.09,2020-03-02,2020-03-05,10,0,Heavy Rain,1.5,74.00,62.0,94.0,NW,2.00,3.0,30.00,0.0,Moderate or heavy rain shower
4902,4888,Vietnam,105.183000,20.691000,50183.18,2020-03-02,2020-03-10,2,1000,Heavy Rain,1.0,77.00,67.0,90.0,S,3.00,4.0,31.00,0.0,Partly cloudy
4903,4891,Spain,-0.101059,40.132000,4269.15,2020-04-01,2020-04-02,0,91,Torrential Rain,1.5,56.00,34.0,57.0,NW,3.00,5.0,31.00,0.0,Partly cloudy
4904,4892,Papua New Guinea,146.752000,-6.925130,14567.65,2020-04-01,2020-04-03,0,0,Heavy Rain,1.0,82.00,73.0,90.0,SW,4.00,8.0,30.00,0.2,Light rain shower
4905,4894,Afghanistan,65.642400,33.826000,220551.72,2020-03-21,2020-04-03,11,1200,Heavy Rain,1.5,42.00,32.0,81.0,ESE,5.00,6.0,31.00,0.0,Partly cloudy
4906,4895,Zambia,30.902500,-10.090100,91521.53,2020-03-04,2020-04-24,0,0,Heavy Rain,1.5,73.00,62.0,95.0,NNW,4.00,8.0,30.00,0.0,Light rain shower
4907,4896,Democratic Republic of Congo,26.745600,-3.244940,180311.71,2020-03-17,2020-04-03,36,78000,Heavy Rain,2.0,70.00,70.0,99.0,S,2.00,4.0,30.00,0.1,Torrential rain shower
4908,4897,Kenya,36.593500,1.163430,154389.90,2020-03-27,2020-04-27,1,3000,Heavy Rain,1.5,70.00,51.0,69.0,ENE,6.00,10.0,30.00,0.0,Partly cloudy
4909,4898,Peru,-76.880100,-7.010730,152175.01,2020-03-28,2020-04-02,0,120,Heavy Rain,1.5,84.00,70.0,98.0,WSW,1.00,2.0,31.00,0.1,Light rain shower
4910,4900,Tanzania,34.218200,-4.512360,184333.48,2020-04-24,2020-04-27,2,10000,Heavy Rain,1.5,71.00,63.0,94.0,E,3.00,6.0,30.00,0.0,Light rain shower
4911,4901,Djibouti,42.680400,11.685100,10321.78,2020-04-21,2020-04-26,8,0,Torrential Rain,2.0,85.00,73.0,75.0,ESE,4.00,6.0,30.00,0.0,Partly cloudy
4912,4902,Burkina Faso,-1.115540,13.343200,42577.65,2020-04-19,2020-04-26,0,2000,Torrential Rain,1.5,95.00,51.0,25.0,SSW,8.00,16.0,30.00,0.0,Partly cloudy
4913,4903,Burundi,29.937500,-2.763120,41569.31,2020-04-19,2020-04-26,9,0,Heavy Rain,1.5,72.00,58.0,94.0,W,2.00,4.0,30.00,0.0,Cloudy
4914,4905,Vietnam,106.172000,17.888600,15289.41,2020-04-22,2020-04-26,3,0,Torrential Rain,1.0,82.00,73.0,95.0,WSW,3.00,5.0,30.00,0.0,Patchy rain possible
4915,4906,Angola,14.200700,-9.139080,77631.98,2020-04-18,2020-04-24,11,90,Heavy Rain,1.5,77.00,67.0,99.0,NW,1.00,3.0,30.00,0.0,Fog
4916,4907,New Caledonia,165.854000,-21.488300,8299.71,2020-04-18,2020-04-22,0,0,Torrential Rain,1.0,78.00,72.0,85.0,E,9.00,12.0,31.00,0.0,Light rain shower
4917,4912,Chad,18.085400,9.627940,134488.38,2020-04-20,2020-04-26,0,2062,Heavy Rain,1.0,99.00,39.0,17.0,ENE,2.00,5.0,30.00,0.0,Partly cloudy
4918,4913,Uzbekistan,55.844000,41.245100,84662.22,2020-05-01,2020-05-11,4,70000,Dam break,2.0,64.00,48.0,55.0,WNW,12.00,20.0,30.00,0.0,Partly cloudy
4919,4914,Sri Lanka,80.859700,7.835490,46625.90,2020-05-17,2020-05-20,2,1100,Tropical Storm Amphan,1.5,82.00,74.0,96.0,S,3.00,5.0,30.00,0.2,Light drizzle
4920,4916,Democratic Republic Congo,17.615300,-3.822620,84572.69,2020-05-16,2020-05-20,0,500,Heavy Rain,1.5,79.00,73.0,92.0,SW,2.00,3.0,30.00,0.0,Patchy rain possible
4921,4917,Algeria,12.666600,31.683700,91355.80,2020-05-16,2020-05-18,1,0,Heavy Rain,1.0,87.00,59.0,66.0,N,6.00,8.0,30.00,0.0,Partly cloudy
4922,4918,Ecuador,-77.993600,-2.683770,24825.78,2020-05-16,2020-05-19,2,15,Heavy Rain,1.0,52.00,53.0,83.0,SSE,3.00,5.0,30.00,0.1,Moderate or heavy rain shower
4923,4924,Cental African Republic,17.021400,4.582310,65353.26,2020-05-24,2020-05-30,3,0,Torrential Rain,1.0,79.00,69.0,95.0,SSW,3.00,7.0,30.00,0.1,Patchy rain possible
4924,4925,Uganda,31.026300,0.013018,47454.12,2020-05-21,2020-05-25,8,300,Torrential Rain,1.5,68.00,62.0,95.0,W,1.00,2.0,30.00,0.0,Patchy light drizzle
4925,4928,El Salvador,-89.623000,17.391100,253817.46,2020-06-02,2020-06-03,0,0,Tropical Storm Cristobal,1.5,79.00,71.0,98.0,SW,3.00,6.0,30.00,0.2,Torrential rain shower

In [197]:
df4.dtypes

ID                 int64
Country           object
long             float64
lat              float64
Area             float64
Began             object
Ended             object
Dead               int64
Displaced          int64
MainCause         object
Severity         float64
Temperature      float64
Dew Point        float64
Humidity         float64
Wind              object
Wind Speed       float64
Wind Gust        float64
Pressure         float64
Precipitation    float64
Condition         object
dtype: object

In [198]:
df4.columns =['ID','Country','longitude','latitude','Area','Began','Ended','Dead','Displaced','MainCause','Severity','Day-4_Temperature','Day-4_Dew_Point','Day-4_Humidity','Day-4_Wind','Day-4_Wind_Speed','Day-4_Wind_Gust','Day-4_Pressure','Day-4_Precipitation','Day-4_Condition']

In [199]:
df4.dtypes

ID                       int64
Country                 object
longitude              float64
latitude               float64
Area                   float64
Began                   object
Ended                   object
Dead                     int64
Displaced                int64
MainCause               object
Severity               float64
Day-4_Temperature      float64
Day-4_Dew_Point        float64
Day-4_Humidity         float64
Day-4_Wind              object
Day-4_Wind_Speed       float64
Day-4_Wind_Gust        float64
Day-4_Pressure         float64
Day-4_Precipitation    float64
Day-4_Condition         object
dtype: object

# Merge Data

In [205]:
#merging datasets
df_inner1 = pd.merge(df1, df2, on='ID', how='inner')

In [217]:
df_inner1.dtypes

ID                       int64
Country_x               object
longitude_x            float64
latitude_x             float64
Area_x                 float64
Began_x                 object
Ended_x                 object
Dead_x                   int64
Displaced_x              int64
MainCause_x             object
Severity_x             float64
Day-1_Temperature      float64
Day-1_Dew_Point        float64
Day-1_Humidity         float64
Day-1_Wind              object
Day-1_Wind_Speed       float64
Day-1_Wind_Gust        float64
Day-1_Pressure         float64
Day-1_Precipitation    float64
Day-1_Condition         object
Country_y               object
longitude_y            float64
latitude_y             float64
Area_y                 float64
Began_y                 object
Ended_y                 object
Dead_y                   int64
Displaced_y              int64
MainCause_y             object
Severity_y             float64
Day-2_Temperature      float64
Day-2_Dew_Point        float64
Day-2_Humidity         float64
Day-2_Wind              object
Day-2_Wind_Speed       float64
Day-2_Wind_Gust        float64
Day-2_Pressure         float64
Day-2_Precipitation    float64
Day-2_Condition         object
dtype: object

In [207]:
#merging datasets
df_inner2 = pd.merge(df3, df4, on='ID', how='inner')

In [216]:
df_inner2.dtypes

ID                       int64
Country_x               object
longitude_x            float64
latitude_x             float64
Area_x                 float64
Began_x                 object
Ended_x                 object
Dead_x                   int64
Displaced_x              int64
MainCause_x             object
Severity_x             float64
Day-3_Temperature      float64
Day-3_Dew_Point        float64
Day-3_Humidity         float64
Day-3_Wind              object
Day-3_Wind_Speed       float64
Day-3_Wind_Gust        float64
Day-3_Pressure         float64
Day-3_Precipitation    float64
Day-3_Condition         object
Country_y               object
longitude_y            float64
latitude_y             float64
Area_y                 float64
Began_y                 object
Ended_y                 object
Dead_y                   int64
Displaced_y              int64
MainCause_y             object
Severity_y             float64
Day-4_Temperature      float64
Day-4_Dew_Point        float64
Day-4_Humidity         float64
Day-4_Wind              object
Day-4_Wind_Speed       float64
Day-4_Wind_Gust        float64
Day-4_Pressure         float64
Day-4_Precipitation    float64
Day-4_Condition         object
dtype: object

In [209]:
#merging datasets
df_inner = pd.merge(df_inner1, df_inner2, on='ID', how='inner')

In [218]:
df_inner.dtypes

ID                       int64
Country_x_x             object
longitude_x_x          float64
latitude_x_x           float64
Area_x_x               float64
Began_x_x               object
Ended_x_x               object
Dead_x_x                 int64
Displaced_x_x            int64
MainCause_x_x           object
Severity_x_x           float64
Day-1_Temperature      float64
Day-1_Dew_Point        float64
Day-1_Humidity         float64
Day-1_Wind              object
Day-1_Wind_Speed       float64
Day-1_Wind_Gust        float64
Day-1_Pressure         float64
Day-1_Precipitation    float64
Day-1_Condition         object
Country_y_x             object
longitude_y_x          float64
latitude_y_x           float64
Area_y_x               float64
Began_y_x               object
Ended_y_x               object
Dead_y_x                 int64
Displaced_y_x            int64
MainCause_y_x           object
Severity_y_x           float64
                        ...
MainCause_x_y           object
Severity_x_y           float64
Day-3_Temperature      float64
Day-3_Dew_Point        float64
Day-3_Humidity         float64
Day-3_Wind              object
Day-3_Wind_Speed       float64
Day-3_Wind_Gust        float64
Day-3_Pressure         float64
Day-3_Precipitation    float64
Day-3_Condition         object
Country_y_y             object
longitude_y_y          float64
latitude_y_y           float64
Area_y_y               float64
Began_y_y               object
Ended_y_y               object
Dead_y_y                 int64
Displaced_y_y            int64
MainCause_y_y           object
Severity_y_y           float64
Day-4_Temperature      float64
Day-4_Dew_Point        float64
Day-4_Humidity         float64
Day-4_Wind              object
Day-4_Wind_Speed       float64
Day-4_Wind_Gust        float64
Day-4_Pressure         float64
Day-4_Precipitation    float64
Day-4_Condition         object
Length: 77, dtype: object

In [247]:
df = pd.merge(df0, df_inner, on='ID', how='outer')

In [248]:
df

,ID,Country,longitude,latitude,Area,Began,Ended,Dead,Displaced,MainCause,...,Severity_y_y,Day-4_Temperature,Day-4_Dew_Point,Day-4_Humidity,Day-4_Wind,Day-4_Wind_Speed,Day-4_Wind_Gust,Day-4_Pressure,Day-4_Precipitation,Day-4_Condition
0,1,Algeria,5.23026,35.814200,92615.67,1985-01-01,1985-01-05,26.0,3000.0,Heavy rain,...,1.0,66.20,NaN,88.0,NaN,3.10,NaN,30.12,NaN,Clouds
1,2,Brazil,-45.34890,-18.711100,678498.82,1985-01-15,1985-02-02,229.0,80000.0,Heavy rain,...,2.0,69.51,NaN,61.0,NaN,1.73,NaN,30.12,NaN,Clouds
2,3,Phillipines,122.97400,10.020700,12846.03,1985-01-20,1985-01-21,43.0,444.0,Torrential rain,...,1.0,75.85,NaN,85.0,NaN,1.93,NaN,29.80,NaN,Clouds
3,4,Indonesia,124.60600,1.014890,16542.12,1985-02-04,1985-02-18,21.0,300.0,Torrential rain,...,1.0,87.80,NaN,58.0,NaN,1.00,NaN,29.83,NaN,Clouds
4,5,Mozambique,32.34910,-25.869300,20082.21,1985-02-09,1985-02-11,19.0,0.0,Heavy rain,...,2.0,53.29,NaN,62.0,NaN,4.10,NaN,30.56,NaN,Clear
5,6,Comoros islands,43.36000,-11.651600,1035.61,1985-02-16,1985-02-28,2.0,35000.0,Tropical cyclone,...,1.0,67.95,NaN,87.0,NaN,9.03,NaN,30.03,NaN,Rain
6,7,New Zealand,175.73400,-37.230500,7871.37,1985-02-17,1985-02-18,4.0,200.0,Heavy rain,...,1.0,52.00,NaN,90.0,NaN,8.94,NaN,29.94,NaN,Rain
7,8,Indonesia,108.14000,-7.040080,77091.11,1985-02-19,1985-02-23,10.0,2000.0,Heavy rain,...,1.0,66.00,NaN,96.0,NaN,0.96,NaN,29.85,NaN,Clouds
8,10,Bolivia,-63.28870,-21.224400,69706.89,1985-02-25,1985-02-28,2.0,1000.0,Heavy Rain,...,1.0,61.66,NaN,50.0,NaN,0.91,NaN,29.94,NaN,Clouds
9,13,USA,-96.78450,29.604400,141508.00,1985-03-14,1985-03-15,0.0,0.0,Heavy rain,...,1.0,85.14,NaN,66.0,NaN,4.10,NaN,29.97,NaN,Clear
10,15,Brazil,-48.09870,-4.135190,1970402.21,1985-04-02,1985-04-17,32.0,700000.0,Heavy rain,...,2.0,73.06,NaN,77.0,NaN,1.21,NaN,29.91,NaN,Clear
11,17,China,127.89700,48.091700,300325.08,1985-04-21,1985-04-29,0.0,200.0,Ice jam/break-up,...,1.0,85.71,NaN,44.0,NaN,3.75,NaN,29.59,NaN,Clouds
12,20,USA,-66.70600,18.229100,1423.92,1985-05-19,1985-05-20,2.0,4500.0,Heavy rain,...,1.0,74.98,NaN,93.0,NaN,1.18,NaN,28.29,NaN,Rain
13,21,China,109.57000,25.669400,458666.21,1985-05-26,1985-06-06,64.0,10000.0,Heavy rain,...,2.0,86.00,NaN,66.0,NaN,6.00,NaN,29.71,NaN,Clouds
14,22,Argentina,-58.97350,-35.439200,78653.41,1985-05-30,1985-06-01,25.0,100000.0,Heavy rain,...,2.0,47.79,NaN,56.0,NaN,3.71,NaN,30.21,NaN,Clouds
15,23,Bangladesh,91.85420,24.649700,8910.30,1985-06-03,1985-06-22,7.0,100000.0,Heavy rain,...,2.0,83.19,NaN,82.0,NaN,2.31,NaN,29.68,NaN,Rain
16,26,Philippines,120.91600,14.741700,7768.19,1985-06-22,1985-06-30,98.0,130000.0,Tropical cyclone,...,1.0,88.00,NaN,72.0,NaN,0.89,NaN,29.77,NaN,Clouds
17,27,India,75.09370,14.539800,254234.60,1985-06-23,1985-06-27,95.0,25000.0,Heavy rain,...,1.0,70.41,NaN,92.0,NaN,3.69,NaN,29.68,NaN,Clouds
18,28,China,109.97400,27.788200,290679.68,1985-06-28,1985-07-10,275.0,60000.0,Heavy rain,...,2.0,86.04,NaN,67.0,NaN,3.67,NaN,29.65,NaN,Rain
19,29,Bangladesh,89.98530,22.617600,6446.85,1985-07-03,1985-07-04,2.0,77000.0,Heavy rain,...,1.0,85.93,NaN,72.0,NaN,2.72,NaN,29.62,NaN,Clouds
20,30,West Germany,6.50952,50.713400,1927.64,1985-07-06,1985-07-07,3.0,0.0,Heavy rain,...,1.0,58.10,NaN,93.0,NaN,1.50,NaN,30.00,NaN,Clouds
21,32,Chad,21.55090,11.672700,15243.93,1985-07-13,1985-07-16,0.0,1600.0,Heavy rain,...,1.0,70.23,NaN,86.0,NaN,4.36,NaN,29.91,NaN,Rain
22,33,India,76.91030,32.835300,117441.17,1985-07-18,1985-07-30,340.0,20000.0,Heavy rain,...,1.0,35.74,NaN,83.0,NaN,1.08,NaN,29.85,NaN,Clear
23,34,Sudan,24.91390,13.489000,63577.12,1985-07-19,1985-07-22,0.0,0.0,Heavy rain,...,1.0,78.13,NaN,52.0,NaN,2.78,NaN,29.85,NaN,Clouds
24,35,China,125.15600,42.695300,994498.21,1985-07-20,1985-09-02,200.0,2000000.0,Tropical cyclone,...,2.0,83.62,NaN,48.0,NaN,1.87,NaN,29.68,NaN,Clear
25,36,Bangladesh,90.19990,23.102800,5663.46,1985-07-21,1985-08-17,15.0,175000.0,Heavy rain,...,1.0,85.03,NaN,77.0,NaN,3.03,NaN,29.62,NaN,Clouds
26,38,China,120.37600,31.511200,58279.12,1985-08-01,1985-08-02,3.0,200000.0,Heavy rain,...,1.0,74.86,NaN,73.0,NaN,0.89,NaN,29.53,NaN,Rain
27,40,Nepal,87.12580,27.504900,12487.89,1985-08-04,1985-08-05,3.0,160.0,Heavy Rain,...,2.0,69.87,NaN,80.0,NaN,0.43,NaN,29.80,NaN,Rain
28,41,China,100.79700,23.525500,146691.46,1985-08-06,1985-08-09,283.0,14000.0,Heavy rain,...,1.0,69.42,NaN,90.0,NaN,1.42,NaN,29.77,NaN,Rain
29,42,Austria,12.20660,47.315500,15151.05,1985-08-07,1985-08-08,12.0,0.0,Heavy rain,...,2.0,53.55,NaN,97.0,NaN,0.67,NaN,29.94,NaN,Rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4956,4873,Australia,148.60700,-27.492900,816540.49,2020-02-07,2020-02-17,1.0,0.0,Heavy Rain,...,1.0,91.00,59.0,42.0,SW,15.00,23.0,30.00,0.0,Partly cloudy
4957,4874,Burundi,29.98700,-3.407660,17373.89,2020-02-07,2020-02-17,3.0,1000.0,Heavy Rain,...,1.5,71.00,60.0,95.0,SSW,2.00,4.0,31.00,0.0,Patchy rain possible
4958,4875,Tanzania,35.28210,-7.773570,266334.32,2020-02-01,2020-02-17,40.0,15000.0,Heavy Rain,...,2.0,62.00,60.0,95.0,SE,1.00,1.0,30.00,0.0,Patchy rain possible
4959,4879,Pakistan,71.03650,33.302600,116828.75,2020-03-06,2020-03-17,33.0,1200.0,Heavy Rain,...,1.5,71.00,47.0,59.0,WNW,2.00,5.0,30.00,0.0,Partly cloudy
4960,4882,Zambia,29.96230,-10.250400,101083.20,2020-03-04,2020-03-17,0.0,0.0,Heavy Rain,...,1.5,74.00,63.0,98.0,NE,6.00,11.0,30.00,0.0,Light rain
4961,4884,Burundi,30.08600,-3.085660,13769.59,2020-03-02,2020-03-08,1.0,185.0,Heavy Rain,...,1.5,70.00,61.0,93.0,SW,2.00,4.0,30.00,0.0,Patchy rain possible
4962,4885,Rwanda,29.86330,-1.994450,15283.09,2020-03-02,2020-03-05,10.0,0.0,Heavy Rain,...,1.5,74.00,62.0,94.0,NW,2.00,3.0,30.00,0.0,Moderate or heavy rain shower
4963,4888,Vietnam,105.18300,20.691000,50183.18,2020-03-02,2020-03-10,2.0,1000.0,Heavy Rain,...,1.0,77.00,67.0,90.0,S,3.00,4.0,31.00,0.0,Partly cloudy
4964,4892,Papua New Guinea,146.75200,-6.925130,14567.65,2020-04-01,2020-04-03,0.0,0.0,Heavy Rain,...,1.0,82.00,73.0,90.0,SW,4.00,8.0,30.00,0.2,Light rain shower
4965,4894,Afghanistan,65.64240,33.826000,220551.72,2020-03-21,2020-04-03,11.0,1200.0,Heavy Rain,...,1.5,42.00,32.0,81.0,ESE,5.00,6.0,31.00,0.0,Partly cloudy
4966,4895,Zambia,30.90250,-10.090100,91521.53,2020-03-04,2020-04-24,0.0,0.0,Heavy Rain,...,1.5,73.00,62.0,95.0,NNW,4.00,8.0,30.00,0.0,Light rain shower
4967,4896,Democratic Republic of Congo,26.74560,-3.244940,180311.71,2020-03-17,2020-04-03,36.0,78000.0,Heavy Rain,...,2.0,70.00,70.0,99.0,S,2.00,4.0,30.00,0.1,Torrential rain shower
4968,4897,Kenya,36.59350,1.163430,154389.90,2020-03-27,2020-04-27,1.0,3000.0,Heavy Rain,...,1.5,70.00,51.0,69.0,ENE,6.00,10.0,30.00,0.0,Partly cloudy
4969,4898,Peru,-76.88010,-7.010730,152175.01,2020-03-28,2020-04-02,0.0,120.0,Heavy Rain,...,1.5,84.00,70.0,98.0,WSW,1.00,2.0,31.00,0.1,Light rain shower
4970,4900,Tanzania,34.21820,-4.512360,184333.48,2020-04-24,2020-04-27,2.0,10000.0,Heavy Rain,...,1.5,71.00,63.0,94.0,E,3.00,6.0,30.00,0.0,Light rain shower
4971,4901,Djibouti,42.68040,11.685100,10321.78,2020-04-21,2020-04-26,8.0,0.0,Torrential Rain,...,2.0,85.00,73.0,75.0,ESE,4.00,6.0,30.00,0.0,Partly cloudy
4972,4902,Burkina Faso,-1.11554,13.343200,42577.65,2020-04-19,2020-04-26,0.0,2000.0,Torrential Rain,...,1.5,95.00,51.0,25.0,SSW,8.00,16.0,30.00,0.0,Partly cloudy
4973,4903,Burundi,29.93750,-2.763120,41569.31,2020-04-19,2020-04-26,9.0,0.0,Heavy Rain,...,1.5,72.00,58.0,94.0,W,2.00,4.0,30.00,0.0,Cloudy
4974,4907,New Caledonia,165.85400,-21.488300,8299.71,2020-04-18,2020-04-22,0.0,0.0,Torrential Rain,...,1.0,78.00,72.0,85.0,E,9.00,12.0,31.00,0.0,Light rain shower
4975,4912,Chad,18.08540,9.627940,134488.38,2020-04-20,2020-04-26,0.0,2062.0,Heavy Rain,...,1.0,99.00,39.0,17.0,ENE,2.00,5.0,30.00,0.0,Partly cloudy
4976,4913,Uzbekistan,55.84400,41.245100,84662.22,2020-05-01,2020-05-11,4.0,70000.0,Dam break,...,2.0,64.00,48.0,55.0,WNW,12.00,20.0,30.00,0.0,Partly cloudy
4977,4914,Sri Lanka,80.85970,7.835490,46625.90,2020-05-17,2020-05-20,2.0,1100.0,Tropical Storm Amphan,...,1.5,82.00,74.0,96.0,S,3.00,5.0,30.00,0.2,Light drizzle
4978,4916,Democratic Republic Congo,17.61530,-3.822620,84572.69,2020-05-16,2020-05-20,0.0,500.0,Heavy Rain,...,1.5,79.00,73.0,92.0,SW,2.00,3.0,30.00,0.0,Patchy rain possible
4979,4917,Algeria,12.66660,31.683700,91355.80,2020-05-16,2020-05-18,1.0,0.0,Heavy Rain,...,1.0,87.00,59.0,66.0,N,6.00,8.0,30.00,0.0,Partly cloudy
4980,4918,Ecuador,-77.99360,-2.683770,24825.78,2020-05-16,2020-05-19,2.0,15.0,Heavy Rain,...,1.0,52.00,53.0,83.0,SSE,3.00,5.0,30.00,0.1,Moderate or heavy rain shower
4981,4924,Cental African Republic,17.02140,4.582310,65353.26,2020-05-24,2020-05-30,3.0,0.0,Torrential Rain,...,1.0,79.00,69.0,95.0,SSW,3.00,7.0,30.00,0.1,Patchy rain possible
4982,4925,Uganda,31.02630,0.013018,47454.12,2020-05-21,2020-05-25,8.0,300.0,Torrential Rain,...,1.5,68.00,62.0,95.0,W,1.00,2.0,30.00,0.0,Patchy light drizzle
4983,4928,El Salvador,-89.62300,17.391100,253817.46,2020-06-02,2020-06-03,0.0,0.0,Tropical Storm Cristobal,...,1.5,79.00,71.0,98.0,SW,3.00,6.0,30.00,0.2,Torrential rain shower
4984,257,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,...,1.0,72.72,NaN,95.0,NaN,1.95,NaN,29.91,NaN,Rain
4985,412,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,...,1.0,78.84,NaN,62.0,NaN,1.87,NaN,29.68,NaN,Rain

In [237]:
#df.apply(lambda x: sum(x.isnull()))

In [238]:
df.dtypes

ID                                int64
Country                          object
longitude                       float64
latitude                        float64
Area                            float64
Began                    datetime64[ns]
Ended                    datetime64[ns]
Dead                            float64
Displaced                       float64
MainCause                        object
Severity                        float64
Day0_Temperature                 object
Day0_Dew_Point                   object
Day0_Humidity                    object
Day0_Wind                        object
Day0_Wind_Speed                  object
Day0_Wind_Gust                   object
Day0_Pressure                    object
Day0_Precipitation               object
Day0_Condition                   object
Duration                        float64
Area_Affected_per_day           float64
Country_x_x                      object
longitude_x_x                   float64
latitude_x_x                    float64
Area_x_x                        float64
Began_x_x                        object
Ended_x_x                        object
Dead_x_x                          int64
Displaced_x_x                     int64
                              ...
MainCause_x_y                    object
Severity_x_y                    float64
Day-3_Temperature               float64
Day-3_Dew_Point                 float64
Day-3_Humidity                  float64
Day-3_Wind                       object
Day-3_Wind_Speed                float64
Day-3_Wind_Gust                 float64
Day-3_Pressure                  float64
Day-3_Precipitation             float64
Day-3_Condition                  object
Country_y_y                      object
longitude_y_y                   float64
latitude_y_y                    float64
Area_y_y                        float64
Began_y_y                        object
Ended_y_y                        object
Dead_y_y                          int64
Displaced_y_y                     int64
MainCause_y_y                    object
Severity_y_y                    float64
Day-4_Temperature               float64
Day-4_Dew_Point                 float64
Day-4_Humidity                  float64
Day-4_Wind                       object
Day-4_Wind_Speed                float64
Day-4_Wind_Gust                 float64
Day-4_Pressure                  float64
Day-4_Precipitation             float64
Day-4_Condition                  object
Length: 98, dtype: object

In [249]:
#back up before dropping columns
df.to_csv('D:\\Research Project\\Datasets\\Flood intensity\\data url\\Final Data\\before_dropping_column.csv')

In [239]:
df

,ID,Country,longitude,latitude,Area,Began,Ended,Dead,Displaced,MainCause,...,Severity_y_y,Day-4_Temperature,Day-4_Dew_Point,Day-4_Humidity,Day-4_Wind,Day-4_Wind_Speed,Day-4_Wind_Gust,Day-4_Pressure,Day-4_Precipitation,Day-4_Condition
0,1,Algeria,5.23026,35.814200,92615.67,1985-01-01,1985-01-05,26.0,3000.0,Heavy rain,...,1.0,66.20,NaN,88.0,NaN,3.10,NaN,30.12,NaN,Clouds
1,2,Brazil,-45.34890,-18.711100,678498.82,1985-01-15,1985-02-02,229.0,80000.0,Heavy rain,...,2.0,69.51,NaN,61.0,NaN,1.73,NaN,30.12,NaN,Clouds
2,3,Phillipines,122.97400,10.020700,12846.03,1985-01-20,1985-01-21,43.0,444.0,Torrential rain,...,1.0,75.85,NaN,85.0,NaN,1.93,NaN,29.80,NaN,Clouds
3,4,Indonesia,124.60600,1.014890,16542.12,1985-02-04,1985-02-18,21.0,300.0,Torrential rain,...,1.0,87.80,NaN,58.0,NaN,1.00,NaN,29.83,NaN,Clouds
4,5,Mozambique,32.34910,-25.869300,20082.21,1985-02-09,1985-02-11,19.0,0.0,Heavy rain,...,2.0,53.29,NaN,62.0,NaN,4.10,NaN,30.56,NaN,Clear
5,6,Comoros islands,43.36000,-11.651600,1035.61,1985-02-16,1985-02-28,2.0,35000.0,Tropical cyclone,...,1.0,67.95,NaN,87.0,NaN,9.03,NaN,30.03,NaN,Rain
6,7,New Zealand,175.73400,-37.230500,7871.37,1985-02-17,1985-02-18,4.0,200.0,Heavy rain,...,1.0,52.00,NaN,90.0,NaN,8.94,NaN,29.94,NaN,Rain
7,8,Indonesia,108.14000,-7.040080,77091.11,1985-02-19,1985-02-23,10.0,2000.0,Heavy rain,...,1.0,66.00,NaN,96.0,NaN,0.96,NaN,29.85,NaN,Clouds
8,10,Bolivia,-63.28870,-21.224400,69706.89,1985-02-25,1985-02-28,2.0,1000.0,Heavy Rain,...,1.0,61.66,NaN,50.0,NaN,0.91,NaN,29.94,NaN,Clouds
9,13,USA,-96.78450,29.604400,141508.00,1985-03-14,1985-03-15,0.0,0.0,Heavy rain,...,1.0,85.14,NaN,66.0,NaN,4.10,NaN,29.97,NaN,Clear
10,15,Brazil,-48.09870,-4.135190,1970402.21,1985-04-02,1985-04-17,32.0,700000.0,Heavy rain,...,2.0,73.06,NaN,77.0,NaN,1.21,NaN,29.91,NaN,Clear
11,17,China,127.89700,48.091700,300325.08,1985-04-21,1985-04-29,0.0,200.0,Ice jam/break-up,...,1.0,85.71,NaN,44.0,NaN,3.75,NaN,29.59,NaN,Clouds
12,20,USA,-66.70600,18.229100,1423.92,1985-05-19,1985-05-20,2.0,4500.0,Heavy rain,...,1.0,74.98,NaN,93.0,NaN,1.18,NaN,28.29,NaN,Rain
13,21,China,109.57000,25.669400,458666.21,1985-05-26,1985-06-06,64.0,10000.0,Heavy rain,...,2.0,86.00,NaN,66.0,NaN,6.00,NaN,29.71,NaN,Clouds
14,22,Argentina,-58.97350,-35.439200,78653.41,1985-05-30,1985-06-01,25.0,100000.0,Heavy rain,...,2.0,47.79,NaN,56.0,NaN,3.71,NaN,30.21,NaN,Clouds
15,23,Bangladesh,91.85420,24.649700,8910.30,1985-06-03,1985-06-22,7.0,100000.0,Heavy rain,...,2.0,83.19,NaN,82.0,NaN,2.31,NaN,29.68,NaN,Rain
16,26,Philippines,120.91600,14.741700,7768.19,1985-06-22,1985-06-30,98.0,130000.0,Tropical cyclone,...,1.0,88.00,NaN,72.0,NaN,0.89,NaN,29.77,NaN,Clouds
17,27,India,75.09370,14.539800,254234.60,1985-06-23,1985-06-27,95.0,25000.0,Heavy rain,...,1.0,70.41,NaN,92.0,NaN,3.69,NaN,29.68,NaN,Clouds
18,28,China,109.97400,27.788200,290679.68,1985-06-28,1985-07-10,275.0,60000.0,Heavy rain,...,2.0,86.04,NaN,67.0,NaN,3.67,NaN,29.65,NaN,Rain
19,29,Bangladesh,89.98530,22.617600,6446.85,1985-07-03,1985-07-04,2.0,77000.0,Heavy rain,...,1.0,85.93,NaN,72.0,NaN,2.72,NaN,29.62,NaN,Clouds
20,30,West Germany,6.50952,50.713400,1927.64,1985-07-06,1985-07-07,3.0,0.0,Heavy rain,...,1.0,58.10,NaN,93.0,NaN,1.50,NaN,30.00,NaN,Clouds
21,32,Chad,21.55090,11.672700,15243.93,1985-07-13,1985-07-16,0.0,1600.0,Heavy rain,...,1.0,70.23,NaN,86.0,NaN,4.36,NaN,29.91,NaN,Rain
22,33,India,76.91030,32.835300,117441.17,1985-07-18,1985-07-30,340.0,20000.0,Heavy rain,...,1.0,35.74,NaN,83.0,NaN,1.08,NaN,29.85,NaN,Clear
23,34,Sudan,24.91390,13.489000,63577.12,1985-07-19,1985-07-22,0.0,0.0,Heavy rain,...,1.0,78.13,NaN,52.0,NaN,2.78,NaN,29.85,NaN,Clouds
24,35,China,125.15600,42.695300,994498.21,1985-07-20,1985-09-02,200.0,2000000.0,Tropical cyclone,...,2.0,83.62,NaN,48.0,NaN,1.87,NaN,29.68,NaN,Clear
25,36,Bangladesh,90.19990,23.102800,5663.46,1985-07-21,1985-08-17,15.0,175000.0,Heavy rain,...,1.0,85.03,NaN,77.0,NaN,3.03,NaN,29.62,NaN,Clouds
26,38,China,120.37600,31.511200,58279.12,1985-08-01,1985-08-02,3.0,200000.0,Heavy rain,...,1.0,74.86,NaN,73.0,NaN,0.89,NaN,29.53,NaN,Rain
27,40,Nepal,87.12580,27.504900,12487.89,1985-08-04,1985-08-05,3.0,160.0,Heavy Rain,...,2.0,69.87,NaN,80.0,NaN,0.43,NaN,29.80,NaN,Rain
28,41,China,100.79700,23.525500,146691.46,1985-08-06,1985-08-09,283.0,14000.0,Heavy rain,...,1.0,69.42,NaN,90.0,NaN,1.42,NaN,29.77,NaN,Rain
29,42,Austria,12.20660,47.315500,15151.05,1985-08-07,1985-08-08,12.0,0.0,Heavy rain,...,2.0,53.55,NaN,97.0,NaN,0.67,NaN,29.94,NaN,Rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4956,4873,Australia,148.60700,-27.492900,816540.49,2020-02-07,2020-02-17,1.0,0.0,Heavy Rain,...,1.0,91.00,59.0,42.0,SW,15.00,23.0,30.00,0.0,Partly cloudy
4957,4874,Burundi,29.98700,-3.407660,17373.89,2020-02-07,2020-02-17,3.0,1000.0,Heavy Rain,...,1.5,71.00,60.0,95.0,SSW,2.00,4.0,31.00,0.0,Patchy rain possible
4958,4875,Tanzania,35.28210,-7.773570,266334.32,2020-02-01,2020-02-17,40.0,15000.0,Heavy Rain,...,2.0,62.00,60.0,95.0,SE,1.00,1.0,30.00,0.0,Patchy rain possible
4959,4879,Pakistan,71.03650,33.302600,116828.75,2020-03-06,2020-03-17,33.0,1200.0,Heavy Rain,...,1.5,71.00,47.0,59.0,WNW,2.00,5.0,30.00,0.0,Partly cloudy
4960,4882,Zambia,29.96230,-10.250400,101083.20,2020-03-04,2020-03-17,0.0,0.0,Heavy Rain,...,1.5,74.00,63.0,98.0,NE,6.00,11.0,30.00,0.0,Light rain
4961,4884,Burundi,30.08600,-3.085660,13769.59,2020-03-02,2020-03-08,1.0,185.0,Heavy Rain,...,1.5,70.00,61.0,93.0,SW,2.00,4.0,30.00,0.0,Patchy rain possible
4962,4885,Rwanda,29.86330,-1.994450,15283.09,2020-03-02,2020-03-05,10.0,0.0,Heavy Rain,...,1.5,74.00,62.0,94.0,NW,2.00,3.0,30.00,0.0,Moderate or heavy rain shower
4963,4888,Vietnam,105.18300,20.691000,50183.18,2020-03-02,2020-03-10,2.0,1000.0,Heavy Rain,...,1.0,77.00,67.0,90.0,S,3.00,4.0,31.00,0.0,Partly cloudy
4964,4892,Papua New Guinea,146.75200,-6.925130,14567.65,2020-04-01,2020-04-03,0.0,0.0,Heavy Rain,...,1.0,82.00,73.0,90.0,SW,4.00,8.0,30.00,0.2,Light rain shower
4965,4894,Afghanistan,65.64240,33.826000,220551.72,2020-03-21,2020-04-03,11.0,1200.0,Heavy Rain,...,1.5,42.00,32.0,81.0,ESE,5.00,6.0,31.00,0.0,Partly cloudy
4966,4895,Zambia,30.90250,-10.090100,91521.53,2020-03-04,2020-04-24,0.0,0.0,Heavy Rain,...,1.5,73.00,62.0,95.0,NNW,4.00,8.0,30.00,0.0,Light rain shower
4967,4896,Democratic Republic of Congo,26.74560,-3.244940,180311.71,2020-03-17,2020-04-03,36.0,78000.0,Heavy Rain,...,2.0,70.00,70.0,99.0,S,2.00,4.0,30.00,0.1,Torrential rain shower
4968,4897,Kenya,36.59350,1.163430,154389.90,2020-03-27,2020-04-27,1.0,3000.0,Heavy Rain,...,1.5,70.00,51.0,69.0,ENE,6.00,10.0,30.00,0.0,Partly cloudy
4969,4898,Peru,-76.88010,-7.010730,152175.01,2020-03-28,2020-04-02,0.0,120.0,Heavy Rain,...,1.5,84.00,70.0,98.0,WSW,1.00,2.0,31.00,0.1,Light rain shower
4970,4900,Tanzania,34.21820,-4.512360,184333.48,2020-04-24,2020-04-27,2.0,10000.0,Heavy Rain,...,1.5,71.00,63.0,94.0,E,3.00,6.0,30.00,0.0,Light rain shower
4971,4901,Djibouti,42.68040,11.685100,10321.78,2020-04-21,2020-04-26,8.0,0.0,Torrential Rain,...,2.0,85.00,73.0,75.0,ESE,4.00,6.0,30.00,0.0,Partly cloudy
4972,4902,Burkina Faso,-1.11554,13.343200,42577.65,2020-04-19,2020-04-26,0.0,2000.0,Torrential Rain,...,1.5,95.00,51.0,25.0,SSW,8.00,16.0,30.00,0.0,Partly cloudy
4973,4903,Burundi,29.93750,-2.763120,41569.31,2020-04-19,2020-04-26,9.0,0.0,Heavy Rain,...,1.5,72.00,58.0,94.0,W,2.00,4.0,30.00,0.0,Cloudy
4974,4907,New Caledonia,165.85400,-21.488300,8299.71,2020-04-18,2020-04-22,0.0,0.0,Torrential Rain,...,1.0,78.00,72.0,85.0,E,9.00,12.0,31.00,0.0,Light rain shower
4975,4912,Chad,18.08540,9.627940,134488.38,2020-04-20,2020-04-26,0.0,2062.0,Heavy Rain,...,1.0,99.00,39.0,17.0,ENE,2.00,5.0,30.00,0.0,Partly cloudy
4976,4913,Uzbekistan,55.84400,41.245100,84662.22,2020-05-01,2020-05-11,4.0,70000.0,Dam break,...,2.0,64.00,48.0,55.0,WNW,12.00,20.0,30.00,0.0,Partly cloudy
4977,4914,Sri Lanka,80.85970,7.835490,46625.90,2020-05-17,2020-05-20,2.0,1100.0,Tropical Storm Amphan,...,1.5,82.00,74.0,96.0,S,3.00,5.0,30.00,0.2,Light drizzle
4978,4916,Democratic Republic Congo,17.61530,-3.822620,84572.69,2020-05-16,2020-05-20,0.0,500.0,Heavy Rain,...,1.5,79.00,73.0,92.0,SW,2.00,3.0,30.00,0.0,Patchy rain possible
4979,4917,Algeria,12.66660,31.683700,91355.80,2020-05-16,2020-05-18,1.0,0.0,Heavy Rain,...,1.0,87.00,59.0,66.0,N,6.00,8.0,30.00,0.0,Partly cloudy
4980,4918,Ecuador,-77.99360,-2.683770,24825.78,2020-05-16,2020-05-19,2.0,15.0,Heavy Rain,...,1.0,52.00,53.0,83.0,SSE,3.00,5.0,30.00,0.1,Moderate or heavy rain shower
4981,4924,Cental African Republic,17.02140,4.582310,65353.26,2020-05-24,2020-05-30,3.0,0.0,Torrential Rain,...,1.0,79.00,69.0,95.0,SSW,3.00,7.0,30.00,0.1,Patchy rain possible
4982,4925,Uganda,31.02630,0.013018,47454.12,2020-05-21,2020-05-25,8.0,300.0,Torrential Rain,...,1.5,68.00,62.0,95.0,W,1.00,2.0,30.00,0.0,Patchy light drizzle
4983,4928,El Salvador,-89.62300,17.391100,253817.46,2020-06-02,2020-06-03,0.0,0.0,Tropical Storm Cristobal,...,1.5,79.00,71.0,98.0,SW,3.00,6.0,30.00,0.2,Torrential rain shower
4984,257,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,...,1.0,72.72,NaN,95.0,NaN,1.95,NaN,29.91,NaN,Rain
4985,412,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,...,1.0,78.84,NaN,62.0,NaN,1.87,NaN,29.68,NaN,Rain

In [250]:
#drop unnecessary columns
df.drop(df.columns[[2,3,22,23,24,25,26,27,28,29,30,31,41,42,43,44,45,46,47,48,49,50,60,61,62,63,64,65,66,67,68,69,79,80,81,82,83,84,85,86,87,88]], axis=1, inplace=True)

In [251]:
df.dtypes

ID                                int64
Country                          object
Area                            float64
Began                    datetime64[ns]
Ended                    datetime64[ns]
Dead                            float64
Displaced                       float64
MainCause                        object
Severity                        float64
Day0_Temperature                 object
Day0_Dew_Point                   object
Day0_Humidity                    object
Day0_Wind                        object
Day0_Wind_Speed                  object
Day0_Wind_Gust                   object
Day0_Pressure                    object
Day0_Precipitation               object
Day0_Condition                   object
Duration                        float64
Area_Affected_per_day           float64
Day-1_Temperature               float64
Day-1_Dew_Point                 float64
Day-1_Humidity                  float64
Day-1_Wind                       object
Day-1_Wind_Speed                float64
Day-1_Wind_Gust                 float64
Day-1_Pressure                  float64
Day-1_Precipitation             float64
Day-1_Condition                  object
Day-2_Temperature               float64
Day-2_Dew_Point                 float64
Day-2_Humidity                  float64
Day-2_Wind                       object
Day-2_Wind_Speed                float64
Day-2_Wind_Gust                 float64
Day-2_Pressure                  float64
Day-2_Precipitation             float64
Day-2_Condition                  object
Day-3_Temperature               float64
Day-3_Dew_Point                 float64
Day-3_Humidity                  float64
Day-3_Wind                       object
Day-3_Wind_Speed                float64
Day-3_Wind_Gust                 float64
Day-3_Pressure                  float64
Day-3_Precipitation             float64
Day-3_Condition                  object
Day-4_Temperature               float64
Day-4_Dew_Point                 float64
Day-4_Humidity                  float64
Day-4_Wind                       object
Day-4_Wind_Speed                float64
Day-4_Wind_Gust                 float64
Day-4_Pressure                  float64
Day-4_Precipitation             float64
Day-4_Condition                  object
dtype: object

In [243]:
#back up after dropping columns
df.to_csv('D:\\Research Project\\Datasets\\Flood intensity\\data url\\Final Data\\after_dropping_column.csv')

In [252]:
df.apply(lambda x: sum(x.isnull()))

ID                          0
Country                     2
Area                        2
Began                       2
Ended                       2
Dead                        2
Displaced                   2
MainCause                   5
Severity                    2
Day0_Temperature            2
Day0_Dew_Point           2249
Day0_Humidity               2
Day0_Wind                2379
Day0_Wind_Speed             2
Day0_Wind_Gust           2249
Day0_Pressure               2
Day0_Precipitation       2249
Day0_Condition             59
Duration                    2
Area_Affected_per_day       2
Day-1_Temperature          23
Day-1_Dew_Point          2451
Day-1_Humidity             38
Day-1_Wind               2516
Day-1_Wind_Speed          354
Day-1_Wind_Gust          4299
Day-1_Pressure            109
Day-1_Precipitation      4367
Day-1_Condition            52
Day-2_Temperature          22
Day-2_Dew_Point          2363
Day-2_Humidity             34
Day-2_Wind               2437
Day-2_Wind_Speed          402
Day-2_Wind_Gust          4230
Day-2_Pressure            112
Day-2_Precipitation      4275
Day-2_Condition            57
Day-3_Temperature          22
Day-3_Dew_Point          2364
Day-3_Humidity             39
Day-3_Wind               2453
Day-3_Wind_Speed          436
Day-3_Wind_Gust          4244
Day-3_Pressure            109
Day-3_Precipitation      4286
Day-3_Condition            52
Day-4_Temperature          24
Day-4_Dew_Point          2370
Day-4_Humidity             42
Day-4_Wind               2434
Day-4_Wind_Speed          420
Day-4_Wind_Gust          4229
Day-4_Pressure            101
Day-4_Precipitation      4270
Day-4_Condition            48
dtype: int64

In [253]:
df = df[df['Country'].notnull()]
#manually added the country as it was absent during weather link creation for Day0

In [255]:
df[df['Area'].isnull()]

Empty DataFrame
Columns: [ID, Country, Area, Began, Ended, Dead, Displaced, MainCause, Severity, Day0_Temperature, Day0_Dew_Point, Day0_Humidity, Day0_Wind, Day0_Wind_Speed, Day0_Wind_Gust, Day0_Pressure, Day0_Precipitation, Day0_Condition, Duration, Area_Affected_per_day, Day-1_Temperature, Day-1_Dew_Point, Day-1_Humidity, Day-1_Wind, Day-1_Wind_Speed, Day-1_Wind_Gust, Day-1_Pressure, Day-1_Precipitation, Day-1_Condition, Day-2_Temperature, Day-2_Dew_Point, Day-2_Humidity, Day-2_Wind, Day-2_Wind_Speed, Day-2_Wind_Gust, Day-2_Pressure, Day-2_Precipitation, Day-2_Condition, Day-3_Temperature, Day-3_Dew_Point, Day-3_Humidity, Day-3_Wind, Day-3_Wind_Speed, Day-3_Wind_Gust, Day-3_Pressure, Day-3_Precipitation, Day-3_Condition, Day-4_Temperature, Day-4_Dew_Point, Day-4_Humidity, Day-4_Wind, Day-4_Wind_Speed, Day-4_Wind_Gust, Day-4_Pressure, Day-4_Precipitation, Day-4_Condition]
Index: []

[0 rows x 56 columns]

In [272]:
#Cleaning data
import numpy as np
for i, row in df.iterrows():
    if df.loc[i,"Duration"] == 0:
        df.loc[i,"Area_Affected_per_day"] = df.loc[i,"Area"]
        
    #if df.loc[i,"Day0_Temperature"]  
    #found = df[df['Day0_Temperature'].str.contains('Ã‚')]
    print("type :",type(df['Day0_Temperature']))
    s = pd.Series([df['Day0_Temperature'], np.nan])
    print("s :",s)
    s.str.rstrip('Ã‚')
    print("s :",s)
    break

type : <class 'pandas.core.series.Series'>
s : 0    0        66.2
1       68.59
2       77.79
3   ...
1                                                  NaN
dtype: object
s : 0    0        66.2
1       68.59
2       77.79
3   ...
1                                                  NaN
dtype: object